import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { basename, dirname, join, relative, resolve, sep } from 'node:path';

const OBSOLETE_README_PHRASES = [
  'Content is intentionally empty until authored.',
  'Generated by DEVAI v1.4.5.',
];

const REFERENCE_FAMILIES = [
  {
    name: 'RN',
    pattern: /^RN-[A-Z]+-[0-9]{3}$/,
    directory: 'rules',
  },
  {
    name: 'WF',
    pattern: /^WF-[A-Z]+-[0-9]{3}$/,
    directory: 'workflows',
  },
  {
    name: 'UC',
    pattern: /^UC-[A-Z]+-[0-9]{3}$/,
    directory: 'use-cases',
  },
  {
    name: 'JRN',
    pattern: /^JRN-[A-Z]+-[0-9]{3}$/,
    directory: 'journeys',
  },
];

const JOURNEY_MAPPING = [
  'JRN-PEC-001',
  'JRN-PEC-002',
  'JRN-PEC-003',
  'JRN-PEC-004',
  'JRN-PEC-005',
  'JRN-PEC-006',
  'JRN-PEC-007',
  'JRN-BOAT-001',
  'JRN-BOAT-002',
  'JRN-BOAT-003',
  'JRN-BOAT-004',
  'JRN-BOAT-005',
  'JRN-RAIT-001',
  'JRN-RAIT-002',
  'JRN-RAIT-003',
  'JRN-RAIT-004',
  'JRN-TEAT-001',
  'JRN-TEAT-002',
  'JRN-TEAT-003',
  'JRN-TEAT-004',
  'JRN-TEAT-005',
  'JRN-TEAT-006',
  'JRN-DASH-001',
  'JRN-DASH-002',
  'JRN-DASH-003',
  'JRN-DASH-004',
  'JRN-DASH-005',
  'JRN-DASH-006',
  'JRN-DASH-007',
  'JRN-PORTAL-001',
  'JRN-PORTAL-002',
  'JRN-PORTAL-003',
  'JRN-PORTAL-004',
  'JRN-PORTAL-005',
  'JRN-PORTAL-006',
  'JRN-PORTAL-007',
  'JRN-PORTAL-008',
  'JRN-PORTAL-009',
  'JRN-PORTAL-010',
  'JRN-PORTAL-011',
];

const JOURNEY_IDS_BY_SOURCE = new Map(
  JOURNEY_MAPPING.map((sourceId, index) => [
    sourceId,
    `JNY-${String(index + 1).padStart(3, '0')}`,
  ]),
);

function walkFiles(directory) {
  if (!existsSync(directory)) {
    return [];
  }

  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = join(directory, entry.name);
    return entry.isDirectory() ? walkFiles(path) : [path];
  });
}

function relativePath(repoRoot, path) {
  return relative(repoRoot, path).split(sep).join('/');
}

function sha256(bytes) {
  return createHash('sha256').update(bytes).digest('hex');
}

function addViolation(violations, rule, code, path, detail) {
  violations.push({ rule, code, path, detail });
}

function verifySchemaRoster({ repoRoot, packageSchemasDir, violations }) {
  const lawSchemasDir = join(repoRoot, 'law/schemas');
  const packageSchemas = walkFiles(packageSchemasDir)
    .filter((path) => path.endsWith('.schema.json'))
    .map((path) => basename(path))
    .sort();
  const lawSchemas = walkFiles(lawSchemasDir)
    .filter((path) => path.endsWith('.schema.json'))
    .map((path) => basename(path))
    .sort();
  const packageNames = new Set(packageSchemas);
  const lawNames = new Set(lawSchemas);

  for (const name of packageSchemas) {
    const path = join(lawSchemasDir, name);
    if (!lawNames.has(name)) {
      addViolation(
        violations,
        'a',
        'SCHEMA_MISSING',
        relativePath(repoRoot, path),
        `Missing copied schema ${name}.`,
      );
      continue;
    }

    const sourceBytes = readFileSync(join(packageSchemasDir, name));
    const copiedBytes = readFileSync(path);
    if (!sourceBytes.equals(copiedBytes)) {
      addViolation(
        violations,
        'a',
        'SCHEMA_BYTES_DIVERGENT',
        relativePath(repoRoot, path),
        `Copied bytes differ from package schema ${name}.`,
      );
    }
  }

  for (const name of lawSchemas) {
    if (!packageNames.has(name)) {
      addViolation(
        violations,
        'a',
        'SCHEMA_EXTRA',
        relativePath(repoRoot, join(lawSchemasDir, name)),
        `Schema ${name} is outside the package roster.`,
      );
    }
  }

  const manifestPath = join(lawSchemasDir, 'manifest.json');
  let manifest;
  try {
    manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
  } catch {
    addViolation(
      violations,
      'a',
      'MANIFEST_INVALID',
      relativePath(repoRoot, manifestPath),
      'Manifest must be valid JSON.',
    );
    return;
  }

  const manifestHashes = manifest.sha256;
  if (!manifestHashes || typeof manifestHashes !== 'object') {
    addViolation(
      violations,
      'a',
      'MANIFEST_HASHES_MISSING',
      relativePath(repoRoot, manifestPath),
      'Manifest must contain a sha256 object.',
    );
    return;
  }

  const manifestNames = Object.keys(manifestHashes).sort();
  if (
    manifestNames.length !== packageSchemas.length ||
    manifestNames.some((name, index) => name !== packageSchemas[index])
  ) {
    addViolation(
      violations,
      'a',
      'MANIFEST_ROSTER_DIVERGENT',
      relativePath(repoRoot, manifestPath),
      'Manifest sha256 keys must equal the package schema roster.',
    );
  }

  for (const name of packageSchemas) {
    const expectedHash = sha256(readFileSync(join(packageSchemasDir, name)));
    if (manifestHashes[name] !== expectedHash) {
      addViolation(
        violations,
        'a',
        'MANIFEST_HASH_DIVERGENT',
        relativePath(repoRoot, manifestPath),
        `Manifest hash for ${name} does not match the package bytes.`,
      );
    }
  }
}

function slugify(text) {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

function headingSlugs(path) {
  return new Set(
    readFileSync(path, 'utf8')
      .split('\n')
      .flatMap((line) => {
        const match = /^#{1,6}\s+(.+?)\s*$/.exec(line);
        const slug = match ? slugify(match[1]) : '';
        return slug ? [slug] : [];
      }),
  );
}

function hasAppId(path, id) {
  const content = readFileSync(path, 'utf8');
  const frontMatter = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/.exec(content);
  return frontMatter
    ? new RegExp(`^id:\\s*${id}\\s*$`, 'm').test(frontMatter[1])
    : false;
}

function hasOdInCanonicalRegistry(odRegistryPath, id) {
  if (!existsSync(odRegistryPath)) {
    return false;
  }

  const row = new RegExp(
    `^\\|\\s*${id.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*\\|`,
  );
  let section = '';
  for (const line of readFileSync(odRegistryPath, 'utf8').split(/\r?\n/)) {
    if (/^##\s+/.test(line)) {
      section = line;
    } else if (
      row.test(line) &&
      (!id.startsWith('OD-R19-') ||
        /^##\s+R-0019\s+—\s+law-corpus\s*$/.test(section))
    ) {
      return true;
    }
  }
  return false;
}

function resolveReference(repoRoot, odRegistryPath, id) {
  const productRoot = join(repoRoot, 'docs/framework/product');
  const family = REFERENCE_FAMILIES.find(({ pattern }) => pattern.test(id));
  if (family) {
    return walkFiles(productRoot).some(
      (path) =>
        basename(path) === `${id}.md` &&
        relative(productRoot, path).split(sep).includes(family.directory),
    );
  }

  if (/^APP-[A-Z0-9]+$/.test(id)) {
    return walkFiles(productRoot).some(
      (path) => basename(path) === 'APP.md' && hasAppId(path, id),
    );
  }

  if (/^ADR-[0-9]{4}$/.test(id)) {
    return [join(repoRoot, 'docs/meta/adr'), join(repoRoot, 'law/adr')].some(
      (directory) =>
        walkFiles(directory).some((path) =>
          new RegExp(`^${id}-.*\\.md$`).test(basename(path)),
        ),
    );
  }

  if (/^OD(?:-[A-Z0-9]+)*-[0-9]{3}$/.test(id)) {
    return hasOdInCanonicalRegistry(odRegistryPath, id);
  }

  return false;
}

function isFileInside(repoRoot, path) {
  const target = resolve(repoRoot, path);
  return target === repoRoot || target.startsWith(`${repoRoot}${sep}`);
}

function verifyProvenance({ repoRoot, odRegistryPath, violations }) {
  const invariantDirectory = join(repoRoot, 'law/invariants');
  for (const path of walkFiles(invariantDirectory).filter((file) =>
    file.endsWith('.json'),
  )) {
    const displayPath = relativePath(repoRoot, path);
    let invariant;
    try {
      invariant = JSON.parse(readFileSync(path, 'utf8'));
    } catch {
      addViolation(
        violations,
        'b',
        'INVARIANT_INVALID',
        displayPath,
        'Invalid JSON.',
      );
      continue;
    }

    for (const id of invariant.provenance ?? []) {
      if (!resolveReference(repoRoot, odRegistryPath, id)) {
        addViolation(
          violations,
          'b',
          'REFERENCE_UNRESOLVED',
          displayPath,
          `Provenance reference ${id} does not resolve.`,
        );
      }
    }

    for (const authorityDoc of invariant.authority_docs?.docs ?? []) {
      const doc = authorityDoc.doc;
      const anchor = authorityDoc.anchor;
      const authorityPath =
        typeof doc === 'string' ? resolve(repoRoot, doc) : null;
      if (
        !authorityPath ||
        !isFileInside(repoRoot, doc) ||
        !existsSync(authorityPath)
      ) {
        addViolation(
          violations,
          'b',
          'AUTHORITY_DOCUMENT_UNRESOLVED',
          displayPath,
          `Authority document ${doc ?? '(missing)'} does not exist.`,
        );
        continue;
      }
      const slugs = statSync(authorityPath).isFile()
        ? headingSlugs(authorityPath)
        : new Set();
      if (
        typeof anchor !== 'string' ||
        (!slugs.has(anchor) && !slugs.has(slugify(anchor)))
      ) {
        addViolation(
          violations,
          'b',
          'AUTHORITY_ANCHOR_UNRESOLVED',
          displayPath,
          `Authority anchor ${anchor ?? '(missing)'} does not resolve in ${doc}.`,
        );
      }
    }
  }
}

function verifyReadmes({ repoRoot, violations }) {
  function isPlaceholderOnly(content, readmePath) {
    const scaffoldHeading = new RegExp(
      `^#\\s+${basename(dirname(readmePath))}\\s*$`,
      'im',
    );
    const body = OBSOLETE_README_PHRASES.reduce(
      (text, phrase) => text.replaceAll(phrase, ''),
      content,
    )
      .replace(scaffoldHeading, '')
      .replace(/^\*\*Authority:\*\*[^\r\n]*$/im, '');
    return !body.trim();
  }

  function isPlaceholderOnlyTree(readmePath) {
    return walkFiles(dirname(readmePath)).every(
      (path) =>
        basename(path) === 'README.md' &&
        isPlaceholderOnly(readFileSync(path, 'utf8'), path),
    );
  }

  for (const directory of [join(repoRoot, 'law'), join(repoRoot, 'product')]) {
    for (const path of walkFiles(directory).filter(
      (file) => basename(file) === 'README.md',
    )) {
      const content = readFileSync(path, 'utf8');
      if (!content.trim()) {
        continue;
      }
      if (isPlaceholderOnly(content, path) && isPlaceholderOnlyTree(path)) {
        continue;
      }
      for (const phrase of OBSOLETE_README_PHRASES) {
        if (content.includes(phrase)) {
          addViolation(
            violations,
            'e',
            'README_OBSOLETE_CONTENT',
            relativePath(repoRoot, path),
            `README contains obsolete phrase: ${phrase}`,
          );
        }
      }
    }
  }
}

function readJson(path, rule, violations) {
  try {
    return JSON.parse(readFileSync(path, 'utf8'));
  } catch {
    addViolation(
      violations,
      rule,
      'ARTIFACT_INVALID',
      path,
      'Artifact must be valid JSON.',
    );
    return null;
  }
}

function canonicalText(value) {
  return typeof value === 'string'
    ? value
        .normalize('NFC')
        .trim()
        .replace(/\s+/g, ' ')
        .toLocaleLowerCase('pt-BR')
    : null;
}

function frontMatterValue(path, key) {
  const content = readFileSync(path, 'utf8');
  const frontMatter = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/.exec(content);
  const match = frontMatter
    ? new RegExp(`^${key}:\\s*(.+?)\\s*$`, 'm').exec(frontMatter[1])
    : null;
  return match?.[1] ?? null;
}

function glossarySourceTerms(repoRoot) {
  const path = join(repoRoot, 'docs/framework/glossary/domain.md');
  if (!existsSync(path)) {
    return { path, terms: new Map() };
  }

  const terms = new Map();
  for (const line of readFileSync(path, 'utf8').split(/\r?\n/)) {
    const cells = line
      .split('|')
      .map((cell) => cell.trim())
      .slice(1, -1);
    if (
      cells.length < 3 ||
      !cells[0] ||
      cells[0] === 'Termo' ||
      /^-+$/.test(cells[0])
    ) {
      continue;
    }
    const term = cells[0];
    const canonicalTerm = canonicalText(term);
    if (canonicalTerm) {
      terms.set(canonicalTerm, term);
    }
  }
  return { path, terms };
}

function verifyGlossaryParity({ repoRoot, violations }) {
  const source = glossarySourceTerms(repoRoot);
  const glossaryDirectory = join(repoRoot, 'law/glossary');
  const entries = new Map();

  for (const path of walkFiles(glossaryDirectory).filter((file) =>
    /^GE-[0-9]{3}\.json$/.test(basename(file)),
  )) {
    const entry = readJson(path, 'c', violations);
    if (!entry) {
      continue;
    }
    const displayPath = relativePath(repoRoot, path);
    const term = canonicalText(entry.term);
    if (!term) {
      addViolation(
        violations,
        'c',
        'GLOSSARY_TERM_INVALID',
        displayPath,
        'GE term is required.',
      );
      continue;
    }
    if (entries.has(term)) {
      addViolation(
        violations,
        'c',
        'GLOSSARY_TERM_DUPLICATE',
        displayPath,
        `Duplicate canonical term ${entry.term}.`,
      );
    }
    entries.set(term, { entry, path: displayPath });
    if (entry.status !== 'draft') {
      addViolation(
        violations,
        'c',
        'GLOSSARY_STATUS_INVALID',
        displayPath,
        'GE status must be draft.',
      );
    }
    if (!Array.isArray(entry.provenance) || entry.provenance.length === 0) {
      addViolation(
        violations,
        'c',
        'GLOSSARY_PROVENANCE_MISSING',
        displayPath,
        'GE provenance is required.',
      );
    }
    for (const invariantId of entry.related_invariants ?? []) {
      if (
        !existsSync(join(repoRoot, 'law/invariants', `${invariantId}.json`))
      ) {
        addViolation(
          violations,
          'c',
          'GLOSSARY_INVARIANT_UNRESOLVED',
          displayPath,
          `Related invariant ${invariantId} does not resolve.`,
        );
      }
    }
  }

  for (const [term, sourceTerm] of source.terms) {
    if (!entries.has(term)) {
      addViolation(
        violations,
        'c',
        'GLOSSARY_SOURCE_MISSING',
        relativePath(repoRoot, source.path),
        `Source term ${sourceTerm} has no GE.`,
      );
    }
  }
  for (const [term, { entry, path }] of entries) {
    if (!source.terms.has(term)) {
      addViolation(
        violations,
        'c',
        'GLOSSARY_ENTRY_ORPHAN',
        path,
        `GE term ${entry.term} does not occur in domain.md.`,
      );
    }
  }
}

function sourceRecords(repoRoot, family, directory, violations) {
  const root = join(repoRoot, 'docs/framework/product');
  const records = new Map();
  for (const path of walkFiles(root).filter((file) =>
    basename(file).endsWith('.md'),
  )) {
    const pathParts = relative(root, path).split(sep);
    const directoryIndex = pathParts.lastIndexOf(directory);
    if (directoryIndex === -1) {
      continue;
    }
    const id = frontMatterValue(path, 'id');
    if (!new RegExp(`^${family}-[A-Z]+-[0-9]{3}$`).test(id ?? '')) {
      continue;
    }
    if (records.has(id)) {
      addViolation(
        violations,
        'd',
        'SOURCE_ID_DUPLICATE',
        relativePath(repoRoot, path),
        `Source ${family} id ${id} is duplicated.`,
      );
      continue;
    }
    records.set(id, {
      path: relativePath(repoRoot, path),
      title: frontMatterValue(path, 'title'),
      bundle: pathParts[directoryIndex - 1],
    });
  }
  return records;
}

function verifyProductParity({ repoRoot, violations }) {
  const journeys = sourceRecords(repoRoot, 'JRN', 'journeys', violations);
  const journeyDirectory = join(repoRoot, 'product/journeys');
  const journeySources = new Map();
  for (const path of walkFiles(journeyDirectory).filter((file) =>
    /^JNY-[0-9]{3}\.json$/.test(basename(file)),
  )) {
    const journey = readJson(path, 'd', violations);
    if (!journey) {
      continue;
    }
    const displayPath = relativePath(repoRoot, path);
    const sourceId = Array.isArray(journey.provenance)
      ? journey.provenance.find((id) => /^JRN-[A-Z]+-[0-9]{3}$/.test(id))
      : null;
    if (!sourceId || !journeys.has(sourceId)) {
      addViolation(
        violations,
        'd',
        'JOURNEY_ORPHAN',
        displayPath,
        `Journey provenance ${sourceId ?? '(missing)'} does not resolve.`,
      );
    } else {
      journeySources.set(sourceId, displayPath);
      const source = journeys.get(sourceId);
      const expectedId = JOURNEY_IDS_BY_SOURCE.get(sourceId);
      if (
        (expectedId && journey.id !== expectedId) ||
        (source.title &&
          canonicalText(journey.title) !== canonicalText(source.title))
      ) {
        addViolation(
          violations,
          'd',
          'JOURNEY_DIVERGENT',
          displayPath,
          `JNY must preserve the fixed mapping and title of ${sourceId}.`,
        );
      }
    }
    if (
      journey.status !== 'draft' ||
      !journey.persona?.role ||
      !Array.isArray(journey.preconditions) ||
      !Array.isArray(journey.postconditions) ||
      !Array.isArray(journey.steps) ||
      journey.steps.length === 0 ||
      !Array.isArray(journey.acceptance_criteria) ||
      journey.acceptance_criteria.length === 0
    ) {
      addViolation(
        violations,
        'd',
        'JOURNEY_CONTENT_INCOMPLETE',
        displayPath,
        'JNY must have draft status, persona, conditions, steps, and acceptance criteria.',
      );
    }
  }
  for (const [id, source] of journeys) {
    if (!journeySources.has(id)) {
      addViolation(
        violations,
        'd',
        'JOURNEY_SOURCE_MISSING',
        source.path,
        `Source journey ${id} has no JNY.`,
      );
    }
  }
  if (journeys.size !== 40) {
    addViolation(
      violations,
      'd',
      'JOURNEY_SOURCE_COUNT_DIVERGENT',
      'docs/framework/product',
      `Expected 40 JRN sources; found ${journeys.size}.`,
    );
  }
  if (journeySources.size !== 40) {
    addViolation(
      violations,
      'd',
      'JOURNEY_OUTPUT_COUNT_DIVERGENT',
      'product/journeys',
      `Expected 40 JNY artifacts; found ${journeySources.size}.`,
    );
  }

  const useCases = sourceRecords(repoRoot, 'UC', 'use-cases', violations);
  const bundledCases = new Map();
  const bundleDirectory = join(repoRoot, 'product/use-cases');
  for (const path of walkFiles(bundleDirectory).filter((file) =>
    file.endsWith('.json'),
  )) {
    const bundle = readJson(path, 'd', violations);
    if (!bundle) {
      continue;
    }
    const displayPath = relativePath(repoRoot, path);
    const bundleRoles = new Set(
      Array.isArray(bundle.roles) ? bundle.roles : [],
    );
    for (const useCase of bundle.cases ?? []) {
      if (!useCase?.id) {
        continue;
      }
      if (bundledCases.has(useCase.id)) {
        addViolation(
          violations,
          'd',
          'BUNDLE_ID_DUPLICATE',
          displayPath,
          `Bundle case id ${useCase.id} is duplicated.`,
        );
        continue;
      }
      bundledCases.set(useCase.id, {
        useCase,
        path: displayPath,
        bundle: basename(path, '.json'),
      });
      if (
        !Array.isArray(useCase.actors) ||
        useCase.actors.some((actor) => !bundleRoles.has(actor))
      ) {
        addViolation(
          violations,
          'd',
          'USE_CASE_ROLE_UNDECLARED',
          displayPath,
          `Bundle roles must contain every actor for ${useCase.id}.`,
        );
      }
    }
  }
  for (const [id, source] of useCases) {
    const bundled = bundledCases.get(id);
    if (!bundled) {
      addViolation(
        violations,
        'd',
        'USE_CASE_SOURCE_MISSING',
        source.path,
        `Source use case ${id} has no bundle entry.`,
      );
      continue;
    }
    if (
      bundled.bundle !== source.bundle ||
      bundled.useCase.title !== source.title ||
      !Array.isArray(bundled.useCase.actors) ||
      bundled.useCase.actors.length === 0
    ) {
      addViolation(
        violations,
        'd',
        'USE_CASE_DIVERGENT',
        bundled.path,
        `Bundle entry ${id} must preserve its source bundle, title, and actors.`,
      );
    }
  }
  for (const [id, bundled] of bundledCases) {
    if (!useCases.has(id)) {
      addViolation(
        violations,
        'd',
        'USE_CASE_ENTRY_ORPHAN',
        bundled.path,
        `Bundle entry ${id} has no source use case.`,
      );
    }
  }
  if (useCases.size !== 110) {
    addViolation(
      violations,
      'd',
      'USE_CASE_SOURCE_COUNT_DIVERGENT',
      'docs/framework/product',
      `Expected 110 UC sources; found ${useCases.size}.`,
    );
  }
  if (bundledCases.size !== 110) {
    addViolation(
      violations,
      'd',
      'USE_CASE_OUTPUT_COUNT_DIVERGENT',
      'product/use-cases',
      `Expected 110 bundled use cases; found ${bundledCases.size}.`,
    );
  }
}

export function verifyLawCorpus({
  repoRoot,
  packageSchemasDir,
  odRegistryPath,
}) {
  const violations = [];
  verifySchemaRoster({ repoRoot, packageSchemasDir, violations });
  verifyProvenance({ repoRoot, odRegistryPath, violations });
  verifyGlossaryParity({ repoRoot, violations });
  verifyProductParity({ repoRoot, violations });
  verifyReadmes({ repoRoot, violations });
  return { violations };
}

function parseArguments(argumentsList) {
  const values = {
    repoRoot: process.cwd(),
    packageSchemasDir: join(
      process.cwd(),
      'node_modules/@aarusso-nyx/devai/dist/runtime/index/schemas',
    ),
    odRegistryPath: join(
      process.cwd(),
      'docs/meta/knowledge-base/open-decisions-rait.md',
    ),
  };
  const keys = {
    '--repo-root': 'repoRoot',
    '--package-schemas-dir': 'packageSchemasDir',
    '--od-registry': 'odRegistryPath',
  };

  for (let index = 0; index < argumentsList.length; index += 2) {
    const key = keys[argumentsList[index]];
    const value = argumentsList[index + 1];
    if (!key || !value) {
      throw new Error(
        `Expected --repo-root, --package-schemas-dir, or --od-registry with a value.`,
      );
    }
    values[key] = resolve(value);
  }
  return values;
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === resolve(import.meta.filename ?? process.argv[1])
) {
  const result = verifyLawCorpus(parseArguments(process.argv.slice(2)));
  for (const violation of result.violations) {
    process.stderr.write(
      `[${violation.rule}] ${violation.code} ${violation.path}: ${violation.detail}\n`,
    );
  }
  process.exitCode = result.violations.length === 0 ? 0 : 1;
}
