import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { basename, dirname, join, relative, resolve, sep } from 'node:path';

const OBSOLETE_README_PHRASES = [
  'Content is intentionally empty until authored.',
  'Generated by DEVAI v1.4.5.',
];

const REFERENCE_FAMILIES = [
  {
    name: 'RN',
    pattern: /^RN-[A-Z]+-[0-9]{3}$/,
    directory: 'rules',
  },
  {
    name: 'WF',
    pattern: /^WF-[A-Z]+-[0-9]{3}$/,
    directory: 'workflows',
  },
  {
    name: 'UC',
    pattern: /^UC-[A-Z]+-[0-9]{3}$/,
    directory: 'use-cases',
  },
  {
    name: 'JRN',
    pattern: /^JRN-[A-Z]+-[0-9]{3}$/,
    directory: 'journeys',
  },
];

function walkFiles(directory) {
  if (!existsSync(directory)) {
    return [];
  }

  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = join(directory, entry.name);
    return entry.isDirectory() ? walkFiles(path) : [path];
  });
}

function relativePath(repoRoot, path) {
  return relative(repoRoot, path).split(sep).join('/');
}

function sha256(bytes) {
  return createHash('sha256').update(bytes).digest('hex');
}

function addViolation(violations, rule, code, path, detail) {
  violations.push({ rule, code, path, detail });
}

function verifySchemaRoster({ repoRoot, packageSchemasDir, violations }) {
  const lawSchemasDir = join(repoRoot, 'law/schemas');
  const packageSchemas = walkFiles(packageSchemasDir)
    .filter((path) => path.endsWith('.schema.json'))
    .map((path) => basename(path))
    .sort();
  const lawSchemas = walkFiles(lawSchemasDir)
    .filter((path) => path.endsWith('.schema.json'))
    .map((path) => basename(path))
    .sort();
  const packageNames = new Set(packageSchemas);
  const lawNames = new Set(lawSchemas);

  for (const name of packageSchemas) {
    const path = join(lawSchemasDir, name);
    if (!lawNames.has(name)) {
      addViolation(
        violations,
        'a',
        'SCHEMA_MISSING',
        relativePath(repoRoot, path),
        `Missing copied schema ${name}.`,
      );
      continue;
    }

    const sourceBytes = readFileSync(join(packageSchemasDir, name));
    const copiedBytes = readFileSync(path);
    if (!sourceBytes.equals(copiedBytes)) {
      addViolation(
        violations,
        'a',
        'SCHEMA_BYTES_DIVERGENT',
        relativePath(repoRoot, path),
        `Copied bytes differ from package schema ${name}.`,
      );
    }
  }

  for (const name of lawSchemas) {
    if (!packageNames.has(name)) {
      addViolation(
        violations,
        'a',
        'SCHEMA_EXTRA',
        relativePath(repoRoot, join(lawSchemasDir, name)),
        `Schema ${name} is outside the package roster.`,
      );
    }
  }

  const manifestPath = join(lawSchemasDir, 'manifest.json');
  let manifest;
  try {
    manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
  } catch {
    addViolation(
      violations,
      'a',
      'MANIFEST_INVALID',
      relativePath(repoRoot, manifestPath),
      'Manifest must be valid JSON.',
    );
    return;
  }

  const manifestHashes = manifest.sha256;
  if (!manifestHashes || typeof manifestHashes !== 'object') {
    addViolation(
      violations,
      'a',
      'MANIFEST_HASHES_MISSING',
      relativePath(repoRoot, manifestPath),
      'Manifest must contain a sha256 object.',
    );
    return;
  }

  const manifestNames = Object.keys(manifestHashes).sort();
  if (
    manifestNames.length !== packageSchemas.length ||
    manifestNames.some((name, index) => name !== packageSchemas[index])
  ) {
    addViolation(
      violations,
      'a',
      'MANIFEST_ROSTER_DIVERGENT',
      relativePath(repoRoot, manifestPath),
      'Manifest sha256 keys must equal the package schema roster.',
    );
  }

  for (const name of packageSchemas) {
    const expectedHash = sha256(readFileSync(join(packageSchemasDir, name)));
    if (manifestHashes[name] !== expectedHash) {
      addViolation(
        violations,
        'a',
        'MANIFEST_HASH_DIVERGENT',
        relativePath(repoRoot, manifestPath),
        `Manifest hash for ${name} does not match the package bytes.`,
      );
    }
  }
}

function slugify(text) {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

function headingSlugs(path) {
  return new Set(
    readFileSync(path, 'utf8')
      .split('\n')
      .flatMap((line) => {
        const match = /^#{1,6}\s+(.+?)\s*$/.exec(line);
        const slug = match ? slugify(match[1]) : '';
        return slug ? [slug] : [];
      }),
  );
}

function hasAppId(path, id) {
  const content = readFileSync(path, 'utf8');
  const frontMatter = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/.exec(content);
  return frontMatter
    ? new RegExp(`^id:\\s*${id}\\s*$`, 'm').test(frontMatter[1])
    : false;
}

function hasOdInCanonicalRegistry(odRegistryPath, id) {
  if (!existsSync(odRegistryPath)) {
    return false;
  }

  const row = new RegExp(
    `^\\|\\s*${id.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*\\|`,
  );
  let section = '';
  for (const line of readFileSync(odRegistryPath, 'utf8').split(/\r?\n/)) {
    if (/^##\s+/.test(line)) {
      section = line;
    } else if (
      row.test(line) &&
      (!id.startsWith('OD-R19-') ||
        /^##\s+R-0019\s+—\s+law-corpus\s*$/.test(section))
    ) {
      return true;
    }
  }
  return false;
}

function resolveReference(repoRoot, odRegistryPath, id) {
  const productRoot = join(repoRoot, 'docs/framework/product');
  const family = REFERENCE_FAMILIES.find(({ pattern }) => pattern.test(id));
  if (family) {
    return walkFiles(productRoot).some(
      (path) =>
        basename(path) === `${id}.md` &&
        relative(productRoot, path).split(sep).includes(family.directory),
    );
  }

  if (/^APP-[A-Z0-9]+$/.test(id)) {
    return walkFiles(productRoot).some(
      (path) => basename(path) === 'APP.md' && hasAppId(path, id),
    );
  }

  if (/^ADR-[0-9]{4}$/.test(id)) {
    return [join(repoRoot, 'docs/meta/adr'), join(repoRoot, 'law/adr')].some(
      (directory) =>
        walkFiles(directory).some((path) =>
          new RegExp(`^${id}-.*\\.md$`).test(basename(path)),
        ),
    );
  }

  if (/^OD(?:-[A-Z0-9]+)*-[0-9]{3}$/.test(id)) {
    return hasOdInCanonicalRegistry(odRegistryPath, id);
  }

  return false;
}

function isFileInside(repoRoot, path) {
  const target = resolve(repoRoot, path);
  return target === repoRoot || target.startsWith(`${repoRoot}${sep}`);
}

function verifyProvenance({ repoRoot, odRegistryPath, violations }) {
  const invariantDirectory = join(repoRoot, 'law/invariants');
  for (const path of walkFiles(invariantDirectory).filter((file) =>
    file.endsWith('.json'),
  )) {
    const displayPath = relativePath(repoRoot, path);
    let invariant;
    try {
      invariant = JSON.parse(readFileSync(path, 'utf8'));
    } catch {
      addViolation(
        violations,
        'b',
        'INVARIANT_INVALID',
        displayPath,
        'Invalid JSON.',
      );
      continue;
    }

    for (const id of invariant.provenance ?? []) {
      if (!resolveReference(repoRoot, odRegistryPath, id)) {
        addViolation(
          violations,
          'b',
          'REFERENCE_UNRESOLVED',
          displayPath,
          `Provenance reference ${id} does not resolve.`,
        );
      }
    }

    for (const authorityDoc of invariant.authority_docs?.docs ?? []) {
      const doc = authorityDoc.doc;
      const anchor = authorityDoc.anchor;
      const authorityPath =
        typeof doc === 'string' ? resolve(repoRoot, doc) : null;
      if (
        !authorityPath ||
        !isFileInside(repoRoot, doc) ||
        !existsSync(authorityPath)
      ) {
        addViolation(
          violations,
          'b',
          'AUTHORITY_DOCUMENT_UNRESOLVED',
          displayPath,
          `Authority document ${doc ?? '(missing)'} does not exist.`,
        );
        continue;
      }
      const slugs = statSync(authorityPath).isFile()
        ? headingSlugs(authorityPath)
        : new Set();
      if (
        typeof anchor !== 'string' ||
        (!slugs.has(anchor) && !slugs.has(slugify(anchor)))
      ) {
        addViolation(
          violations,
          'b',
          'AUTHORITY_ANCHOR_UNRESOLVED',
          displayPath,
          `Authority anchor ${anchor ?? '(missing)'} does not resolve in ${doc}.`,
        );
      }
    }
  }
}

function verifyReadmes({ repoRoot, violations }) {
  function isPlaceholderOnly(content, readmePath) {
    const scaffoldHeading = new RegExp(
      `^#\\s+${basename(dirname(readmePath))}\\s*$`,
      'im',
    );
    const body = OBSOLETE_README_PHRASES.reduce(
      (text, phrase) => text.replaceAll(phrase, ''),
      content,
    )
      .replace(scaffoldHeading, '')
      .replace(/^\*\*Authority:\*\*[^\r\n]*$/im, '');
    return !body.trim();
  }

  function isPlaceholderOnlyTree(readmePath) {
    return walkFiles(dirname(readmePath)).every(
      (path) =>
        basename(path) === 'README.md' &&
        isPlaceholderOnly(readFileSync(path, 'utf8'), path),
    );
  }

  for (const directory of [join(repoRoot, 'law'), join(repoRoot, 'product')]) {
    for (const path of walkFiles(directory).filter(
      (file) => basename(file) === 'README.md',
    )) {
      const content = readFileSync(path, 'utf8');
      if (!content.trim()) {
        continue;
      }
      if (isPlaceholderOnly(content, path) && isPlaceholderOnlyTree(path)) {
        continue;
      }
      for (const phrase of OBSOLETE_README_PHRASES) {
        if (content.includes(phrase)) {
          addViolation(
            violations,
            'e',
            'README_OBSOLETE_CONTENT',
            relativePath(repoRoot, path),
            `README contains obsolete phrase: ${phrase}`,
          );
        }
      }
    }
  }
}

export function verifyLawCorpus({
  repoRoot,
  packageSchemasDir,
  odRegistryPath,
}) {
  const violations = [];
  verifySchemaRoster({ repoRoot, packageSchemasDir, violations });
  verifyProvenance({ repoRoot, odRegistryPath, violations });
  verifyReadmes({ repoRoot, violations });
  return { violations };
}

function parseArguments(argumentsList) {
  const values = {
    repoRoot: process.cwd(),
    packageSchemasDir: join(
      process.cwd(),
      'node_modules/@aarusso-nyx/devai/dist/runtime/index/schemas',
    ),
    odRegistryPath: join(
      process.cwd(),
      'docs/meta/knowledge-base/open-decisions-rait.md',
    ),
  };
  const keys = {
    '--repo-root': 'repoRoot',
    '--package-schemas-dir': 'packageSchemasDir',
    '--od-registry': 'odRegistryPath',
  };

  for (let index = 0; index < argumentsList.length; index += 2) {
    const key = keys[argumentsList[index]];
    const value = argumentsList[index + 1];
    if (!key || !value) {
      throw new Error(
        `Expected --repo-root, --package-schemas-dir, or --od-registry with a value.`,
      );
    }
    values[key] = resolve(value);
  }
  return values;
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === resolve(import.meta.filename ?? process.argv[1])
) {
  const result = verifyLawCorpus(parseArguments(process.argv.slice(2)));
  for (const violation of result.violations) {
    process.stderr.write(
      `[${violation.rule}] ${violation.code} ${violation.path}: ${violation.detail}\n`,
    );
  }
  process.exitCode = result.violations.length === 0 ? 0 : 1;
}
