import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Comece aqui',
      items: [{ type: 'autogenerated', dirName: 'start' }],
    },
    {
      type: 'category',
      label: 'Teoria',
      items: [{ type: 'autogenerated', dirName: 'theory' }],
    },
    {
      type: 'category',
      label: 'Arquitetura',
      items: [{ type: 'autogenerated', dirName: 'framework' }],
    },
    {
      type: 'category',
      label: 'Papéis',
      items: [{ type: 'autogenerated', dirName: 'roles' }],
    },
    {
      type: 'category',
      label: 'Adotantes',
      items: [{ type: 'autogenerated', dirName: 'adopters' }],
    },
    {
      type: 'category',
      label: 'Referências',
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
    {
      type: 'category',
      label: 'Metadados',
      items: [{ type: 'autogenerated', dirName: 'meta' }],
    },
  ],
};

export default sidebars;
