import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Start here',
      items: [{ type: 'autogenerated', dirName: 'start' }],
    },
    {
      type: 'category',
      label: 'Theory',
      items: [{ type: 'autogenerated', dirName: 'theory' }],
    },
    {
      type: 'category',
      label: 'Framework',
      items: [{ type: 'autogenerated', dirName: 'framework' }],
    },
    {
      type: 'category',
      label: 'Roles',
      items: [{ type: 'autogenerated', dirName: 'roles' }],
    },
    {
      type: 'category',
      label: 'Adopters',
      items: [{ type: 'autogenerated', dirName: 'adopters' }],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
    {
      type: 'category',
      label: 'Meta',
      items: [{ type: 'autogenerated', dirName: 'meta' }],
    },
  ],
};

export default sidebars;
