import type { Routes } from '@angular/router';

import type { TeatWebRole } from '../../core/roles.js';
import { productRoute } from '../../data/route-contract.js';

const ROLES: readonly TeatWebRole[] = [
  'processing-operator',
  'traffic-authority',
  'agency-admin',
];

export const FISCALIZACAO_ROUTES: Routes = [
  productRoute({
    path: 'ait-inbox',
    sheet: 'IU-TEAT-ait-inbox',
    uxCode: 'UX-WEB-020',
    allowedRoles: ROLES,
    titleKey: 'teat.screens.ait-inbox.title',
    module: 'fiscalizacao',
    client: 'ait',
    page: 'AitInboxPage',
    sse: true,
  }),
  productRoute({
    path: 'ait-validation',
    sheet: 'IU-TEAT-ait-validation',
    uxCode: 'UX-WEB-021',
    allowedRoles: ROLES,
    titleKey: 'teat.screens.ait-validation.title',
    module: 'fiscalizacao',
    client: 'ait',
    page: 'AitValidationPage',
    contextual: true,
    sse: true,
  }),
  productRoute({
    path: 'ait-sanitization-queue',
    sheet: 'IU-TEAT-ait-sanitization-queue',
    uxCode: 'UX-WEB-022',
    allowedRoles: ROLES,
    titleKey: 'teat.screens.ait-sanitization-queue.title',
    module: 'fiscalizacao',
    client: 'ait',
    page: 'AitSanitizationQueuePage',
    sse: true,
  }),
  productRoute({
    path: 'ait-rejected',
    sheet: 'IU-TEAT-ait-rejected',
    uxCode: 'UX-WEB-023',
    allowedRoles: ROLES,
    titleKey: 'teat.screens.ait-rejected.title',
    module: 'fiscalizacao',
    client: 'ait',
    page: 'AitRejectedPage',
    sse: true,
  }),
  productRoute({
    path: 'ait-detail',
    sheet: 'IU-TEAT-ait-detail',
    uxCode: 'UX-WEB-024',
    allowedRoles: ROLES,
    titleKey: 'teat.screens.ait-detail.title',
    module: 'fiscalizacao',
    client: 'ait',
    page: 'AitDetailPage',
    contextual: true,
    sse: true,
  }),
  productRoute({
    path: 'ait-sanitize',
    sheet: 'IU-TEAT-ait-sanitize',
    uxCode: 'UX-WEB-025',
    allowedRoles: ROLES,
    titleKey: 'teat.screens.ait-sanitize.title',
    module: 'fiscalizacao',
    client: 'ait',
    page: 'AitSanitizePage',
    contextual: true,
    sse: true,
  }),
  productRoute({
    path: 'ait-reject',
    sheet: 'IU-TEAT-ait-reject',
    uxCode: 'UX-WEB-026',
    allowedRoles: ROLES,
    titleKey: 'teat.screens.ait-reject.title',
    module: 'fiscalizacao',
    client: 'ait',
    page: 'AitRejectPage',
    contextual: true,
    sse: true,
  }),
  productRoute({
    path: 'ait-integration',
    sheet: 'IU-TEAT-ait-integration',
    uxCode: 'UX-WEB-027',
    allowedRoles: ROLES,
    titleKey: 'teat.screens.ait-integration.title',
    module: 'fiscalizacao',
    client: 'ait',
    page: 'AitIntegrationPage',
    sse: true,
  }),
  productRoute({
    path: 'ait-mirror',
    sheet: 'IU-TEAT-ait-mirror',
    uxCode: 'UX-WEB-028',
    allowedRoles: ROLES,
    titleKey: 'teat.screens.ait-mirror.title',
    module: 'fiscalizacao',
    client: 'ait',
    page: 'AitMirrorPage',
    sse: true,
  }),
];
