// Manifesto de rotas do console RAIT (plan.md M3/M6/M13; contrato CTG-0002a §2): transcrição
// literal de `work/rounds/R-0012/route-manifest.md` — 74 entradas (72 rotas de
// `rait-web-frontend.md` §4 + as duas auxiliares de A2), na ordem da tabela, mais a tabela A
// (slugs i18n) e as constantes de papéis (`RAIT_ALL_ROLES`, `RAIT_ROLE_PRECEDENCE` = tabela B).
// É a fonte única de `RAIT_ROUTES` (`core/manifest-routes.ts` deriva `title`, guardas e `data`
// de cada entrada) e a tabela que os testes rota × papel e tela ↔ ficha ↔ rota ↔ i18n
// verificam. Não importa `src/testing/` (a fixture do Inspector é transcrição independente).

export type RaitModule =
  | 'core'
  | 'painel'
  | 'fila'
  | 'caso'
  | 'protocolo'
  | 'assinatura'
  | 'autoridade'
  | 'colegiado'
  | 'gestao'
  | 'organizacao'
  | 'integracoes'
  | 'financeiro'
  | 'arquivo'
  | 'auditoria'
  | 'admin'
  | 'conta';

export type RaitRouteKind = 'page' | 'layout' | 'redirect';

/** M13: `L2` página real, `L1` lista/leitura pelos clientes CRUD, `L0` "indisponível nesta versão". */
export type RaitRouteLevel = 'L0' | 'L1' | 'L2';

/**
 * Os 13 códigos canônicos (M4 `todos`): `RAIT_ROLES` de `backend/domains/shared/src/roles.ts`
 * (linhas 57–68) mais os três existentes da spec §3 (`integration-operator`, `AUDITOR`,
 * `agency-admin`).
 */
export const RAIT_ALL_ROLES = [
  'rait-analyst',
  'rait-coordinator',
  'rait-secretary',
  'rait-signing-authority',
  'rait-central-authority',
  'rait-rapporteur',
  'rait-chair',
  'rait-manager',
  'rait-hr',
  'rait-finance',
  'integration-operator',
  'AUDITOR',
  'agency-admin',
] as const;

export type RaitRoleCode = (typeof RAIT_ALL_ROLES)[number];

/**
 * Precedência para união de papéis (ADR-0005): o primeiro presente decide a rota inicial de `/`
 * (route-manifest.md tabela B) e a aba inicial de `/casos/:id` (tabela C).
 */
export const RAIT_ROLE_PRECEDENCE: readonly RaitRoleCode[] = [
  'rait-analyst',
  'rait-rapporteur',
  'rait-secretary',
  'rait-signing-authority',
  'rait-central-authority',
  'rait-chair',
  'rait-manager',
  'rait-coordinator',
  'rait-hr',
  'rait-finance',
  'integration-operator',
  'AUDITOR',
  'agency-admin',
];

export interface RaitRouteEntry {
  /** Como na tabela, sem barra inicial; `''` para `/`. */
  readonly path: string;
  readonly kind: RaitRouteKind;
  /**
   * `T-nn` ou `null`. A forma `T-${string}`/`IU-RAIT-${string}` do contrato §2 é provada por
   * C-2A-02; o tipo fica `string` para que os predicados `screen is string`/`sheet is string`
   * dos specs do Inspector compilem (TS2677 — uma restrição de tipo mais estreita no parâmetro).
   */
  readonly screen: string | null;
  /** `IU-RAIT-nnn` ou `null` (idem). */
  readonly sheet: string | null;
  readonly module: RaitModule;
  /** `'all'` = `todos` (M4). */
  readonly roles: readonly RaitRoleCode[] | 'all';
  readonly resolver: string | null;
  /** `UC-RAIT-nnn` sem colchetes. */
  readonly uc: readonly string[];
  /** `JRN-RAIT-nnn` e `JW-nn` (`JW-01…12` expandido em 12 ids). */
  readonly journeys: readonly string[];
  /** M13 (adenda A3); `null` em `redirect`/`layout`. */
  readonly level: RaitRouteLevel | null;
}

const JW_ALL: readonly string[] = [
  'JW-01',
  'JW-02',
  'JW-03',
  'JW-04',
  'JW-05',
  'JW-06',
  'JW-07',
  'JW-08',
  'JW-09',
  'JW-10',
  'JW-11',
  'JW-12',
];

/** As 74 entradas de `route-manifest.md`, nesta ordem. */
export const RAIT_ROUTE_MANIFEST: readonly RaitRouteEntry[] = [
  {
    path: '',
    kind: 'redirect',
    screen: null,
    sheet: null,
    module: 'core',
    roles: 'all',
    resolver:
      'RoleHomeRedirect: redireciona ao painel do papel principal (tabela B)',
    uc: [],
    journeys: JW_ALL,
    level: null,
  },
  {
    path: 'painel',
    kind: 'page',
    screen: 'T-01',
    sheet: 'IU-RAIT-002',
    module: 'painel',
    roles: 'all',
    resolver: 'resumo do turno (fila, vencendo, diligências, parados)',
    uc: ['UC-RAIT-003'],
    journeys: ['JRN-RAIT-001', ...JW_ALL],
    level: 'L2',
  },
  {
    path: 'painel/retomar',
    kind: 'page',
    screen: 'T-06',
    sheet: 'IU-RAIT-003',
    module: 'painel',
    roles: ['rait-analyst', 'rait-rapporteur'],
    resolver: 'bandeja "prontos para retomar"',
    uc: ['UC-RAIT-003'],
    journeys: ['JRN-RAIT-001', 'JW-01', 'JW-07'],
    level: 'L2',
  },
  {
    path: 'fila/defesa',
    kind: 'page',
    screen: 'T-02',
    sheet: 'IU-RAIT-004',
    module: 'fila',
    roles: ['rait-analyst'],
    resolver: 'fila coletiva do pool defesa_previa + botão "puxar próximo"',
    uc: ['UC-RAIT-003'],
    journeys: ['JRN-RAIT-001', 'JRN-RAIT-003', 'JW-01'],
    level: 'L2',
  },
  {
    path: 'fila/recurso/:orgao',
    kind: 'page',
    screen: 'T-02',
    sheet: 'IU-RAIT-005',
    module: 'fila',
    roles: ['rait-rapporteur'],
    resolver: 'meus casos distribuídos (relatoria)',
    uc: ['UC-RAIT-004'],
    journeys: ['JRN-RAIT-001', 'JRN-RAIT-003', 'JW-07'],
    level: 'L2',
  },
  {
    path: 'casos/:id',
    kind: 'layout',
    screen: 'T-04',
    sheet: 'IU-RAIT-006',
    module: 'caso',
    roles: 'all',
    resolver:
      'layout do caso com abas (resolver: caso, partes, prazos, bandeiras); `caseAccessGuard` todo R-0007 CTG-0004',
    uc: ['UC-RAIT-003'],
    journeys: ['JRN-RAIT-001', ...JW_ALL],
    level: null,
  },
  {
    path: 'casos/:id/resumo',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-007',
    module: 'caso',
    roles: 'all',
    resolver:
      'cabeçalho, estado, relógios, próximas ações (herda papéis de `/casos/:id`)',
    uc: [],
    journeys: JW_ALL,
    level: 'L2',
  },
  {
    path: 'casos/:id/triagem',
    kind: 'page',
    screen: 'T-03',
    sheet: 'IU-RAIT-008',
    module: 'caso',
    roles: ['rait-analyst', 'rait-secretary'],
    resolver: '4 critérios de admissibilidade',
    uc: ['UC-RAIT-002'],
    journeys: ['JRN-RAIT-001', 'JW-01', 'JW-03'],
    level: 'L2',
  },
  {
    path: 'casos/:id/dossie',
    kind: 'page',
    screen: 'T-04',
    sheet: 'IU-RAIT-009',
    module: 'caso',
    roles: 'all',
    resolver: 'documentos, evidências, peças',
    uc: ['UC-RAIT-003'],
    journeys: ['JRN-RAIT-001', ...JW_ALL],
    level: 'L2',
  },
  {
    path: 'casos/:id/diligencias',
    kind: 'page',
    screen: 'T-05',
    sheet: 'IU-RAIT-010',
    module: 'caso',
    roles: ['rait-analyst', 'rait-rapporteur'],
    resolver: 'abrir/responder/prorrogar',
    uc: ['UC-RAIT-003'],
    journeys: ['JRN-RAIT-001', 'JW-01', 'JW-07'],
    level: 'L2',
  },
  {
    path: 'casos/:id/minuta',
    kind: 'page',
    screen: 'T-07',
    sheet: 'IU-RAIT-011',
    module: 'caso',
    roles: ['rait-analyst'],
    resolver: 'editor de minuta (não assina)',
    uc: ['UC-RAIT-003'],
    journeys: ['JRN-RAIT-001', 'JW-01'],
    level: 'L2',
  },
  {
    path: 'casos/:id/decisao',
    kind: 'page',
    screen: 'T-07',
    sheet: 'IU-RAIT-012',
    module: 'caso',
    roles: ['rait-signing-authority'],
    resolver: 'decisão/assinatura (lado autoridade)',
    uc: ['UC-RAIT-003'],
    journeys: ['JRN-RAIT-001', 'JW-05'],
    level: 'L2',
  },
  {
    path: 'casos/:id/prazos',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-013',
    module: 'caso',
    roles: 'all',
    resolver: 'timers, base legal, marcos por canal',
    uc: [],
    journeys: JW_ALL,
    level: 'L2',
  },
  {
    path: 'casos/:id/partes',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-014',
    module: 'caso',
    roles: ['rait-secretary', 'rait-analyst'],
    resolver: 'requerente, procurador, legitimidade',
    uc: [],
    journeys: ['JW-03', 'JW-01'],
    level: 'L2',
  },
  {
    path: 'casos/:id/comunicacoes',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-015',
    module: 'caso',
    roles: ['rait-secretary'],
    resolver: 'envios e marcos de ciência',
    uc: [],
    journeys: ['JW-03'],
    level: 'L2',
  },
  {
    path: 'casos/:id/impedimentos',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-016',
    module: 'caso',
    roles: ['rait-rapporteur', 'rait-chair'],
    resolver: 'declarar impedimento / arguições',
    uc: [],
    journeys: ['JW-07', 'JW-08'],
    level: 'L2',
  },
  {
    path: 'casos/:id/historico',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-017',
    module: 'caso',
    roles: 'all',
    resolver: 'eventos e trilha',
    uc: [],
    journeys: JW_ALL,
    level: 'L2',
  },
  {
    path: 'protocolo',
    kind: 'page',
    screen: 'T-08',
    sheet: 'IU-RAIT-019',
    module: 'protocolo',
    roles: ['rait-secretary'],
    resolver: 'lista de intake do dia',
    uc: ['UC-RAIT-001'],
    journeys: ['JRN-RAIT-003', 'JW-03'],
    level: 'L2',
  },
  {
    path: 'protocolo/novo',
    kind: 'page',
    screen: 'T-08',
    sheet: 'IU-RAIT-020',
    module: 'protocolo',
    roles: ['rait-secretary'],
    resolver: 'cadastro e digitalização de peça física',
    uc: ['UC-RAIT-001'],
    journeys: ['JRN-RAIT-003', 'JW-03'],
    level: 'L2',
  },
  {
    path: 'protocolo/pendencias',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-021',
    module: 'protocolo',
    roles: ['rait-secretary'],
    resolver: 'pendências de conteúdo mínimo',
    uc: ['UC-RAIT-028'],
    journeys: ['JRN-RAIT-003', 'JW-03'],
    level: 'L2',
  },
  {
    path: 'protocolo/remessas',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-022',
    module: 'protocolo',
    roles: ['rait-secretary'],
    resolver: 'F-J-0: remessas à JARI, T-REM10',
    uc: ['UC-RAIT-017'],
    journeys: ['JRN-RAIT-003', 'JW-03'],
    level: 'L2',
  },
  {
    path: 'protocolo/redirecionamentos',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-023',
    module: 'protocolo',
    roles: ['rait-secretary'],
    resolver: 'peças de/para outro órgão',
    uc: ['UC-RAIT-027'],
    journeys: ['JW-03'],
    level: 'L2',
  },
  {
    path: 'protocolo/desistencias',
    kind: 'page',
    screen: 'T-17',
    sheet: 'IU-RAIT-024',
    module: 'protocolo',
    roles: ['rait-secretary'],
    resolver: 'registro de desistência',
    uc: ['UC-RAIT-012'],
    journeys: ['JRN-RAIT-003', 'JW-03'],
    level: 'L2',
  },
  {
    path: 'assinatura',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-025',
    module: 'assinatura',
    roles: ['rait-signing-authority'],
    resolver: 'fila F-DP-5 da circunscrição, ordenada',
    uc: ['UC-RAIT-016'],
    journeys: ['JW-05'],
    level: 'L2',
  },
  {
    path: 'assinatura/:caseId',
    kind: 'page',
    screen: 'T-07',
    sheet: 'IU-RAIT-026',
    module: 'assinatura',
    roles: ['rait-signing-authority'],
    resolver: 'decisão com minuta lado a lado',
    uc: ['UC-RAIT-016'],
    journeys: ['JRN-RAIT-001', 'JW-05'],
    level: 'L2',
  },
  {
    path: 'autoridade/provimentos',
    kind: 'page',
    screen: 'T-16',
    sheet: 'IU-RAIT-027',
    module: 'autoridade',
    roles: ['rait-central-authority'],
    resolver: 'provimentos da JARI a avaliar, dias restantes de T-R2',
    uc: ['UC-RAIT-008'],
    journeys: ['JW-06'],
    level: 'L2',
  },
  {
    path: 'colegiado/:orgao',
    kind: 'redirect',
    screen: null,
    sheet: null,
    module: 'colegiado',
    roles: ['rait-rapporteur', 'rait-chair', 'rait-secretary'],
    resolver: 'raiz de grupo: redireciona ao primeiro filho permitido ao papel',
    uc: [],
    journeys: ['JW-07', 'JW-08', 'JW-04'],
    level: null,
  },
  {
    path: 'colegiado/:orgao/distribuicao',
    kind: 'page',
    screen: 'T-09',
    sheet: 'IU-RAIT-028',
    module: 'colegiado',
    roles: ['rait-chair', 'rait-secretary'],
    resolver: 'lotes de sorteio',
    uc: ['UC-RAIT-014'],
    journeys: ['JRN-RAIT-002', 'JRN-RAIT-003', 'JW-08', 'JW-04'],
    level: 'L2',
  },
  {
    path: 'colegiado/:orgao/distribuicao/:loteId',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-029',
    module: 'colegiado',
    roles: ['rait-chair', 'rait-secretary'],
    resolver: 'ata do lote, aceites, impedimentos',
    uc: ['UC-RAIT-014'],
    journeys: ['JRN-RAIT-002', 'JRN-RAIT-003', 'JW-08', 'JW-04'],
    level: 'L2',
  },
  {
    path: 'colegiado/:orgao/relatoria',
    kind: 'page',
    screen: 'T-10',
    sheet: 'IU-RAIT-030',
    module: 'colegiado',
    roles: ['rait-rapporteur'],
    resolver: 'meus casos, T-VOTO, aceitar lote',
    uc: ['UC-RAIT-004'],
    journeys: ['JRN-RAIT-002', 'JW-07'],
    level: 'L2',
  },
  {
    path: 'colegiado/:orgao/relatoria/:caseId/voto',
    kind: 'page',
    screen: 'T-10',
    sheet: 'IU-RAIT-031',
    module: 'colegiado',
    roles: ['rait-rapporteur'],
    resolver: 'redação do parecer e voto',
    uc: ['UC-RAIT-004'],
    journeys: ['JRN-RAIT-002', 'JW-07'],
    level: 'L2',
  },
  {
    path: 'colegiado/:orgao/pauta',
    kind: 'page',
    screen: 'T-11',
    sheet: 'IU-RAIT-032',
    module: 'colegiado',
    roles: ['rait-chair'],
    resolver: 'montagem e fechamento da pauta',
    uc: ['UC-RAIT-005'],
    journeys: ['JRN-RAIT-002', 'JW-08'],
    level: 'L2',
  },
  {
    path: 'colegiado/:orgao/sessoes',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-033',
    module: 'colegiado',
    roles: ['rait-chair', 'rait-secretary', 'rait-rapporteur'],
    resolver: 'calendário e lista de sessões',
    uc: [],
    journeys: ['JRN-RAIT-002', 'JW-08', 'JW-04', 'JW-07'],
    level: 'L2',
  },
  {
    path: 'colegiado/:orgao/sessoes/:id',
    kind: 'page',
    screen: 'T-12',
    sheet: 'IU-RAIT-034',
    module: 'colegiado',
    roles: ['rait-rapporteur', 'rait-chair', 'rait-secretary'],
    resolver:
      'sessão ao vivo: quorum, itens, votos ("todos do colegiado" = papéis de `/colegiado/:orgao`)',
    uc: ['UC-RAIT-006'],
    journeys: ['JRN-RAIT-002', 'JW-07', 'JW-08', 'JW-04'],
    level: 'L2',
  },
  {
    path: 'colegiado/:orgao/sessoes/:id/banca',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-035',
    module: 'colegiado',
    roles: ['rait-secretary', 'rait-chair'],
    resolver: 'confirmação de banca e suplentes',
    uc: ['UC-RAIT-015'],
    journeys: ['JRN-RAIT-003', 'JW-04', 'JW-08'],
    level: 'L2',
  },
  {
    path: 'colegiado/:orgao/sessoes/:id/ata',
    kind: 'page',
    screen: 'T-13',
    sheet: 'IU-RAIT-036',
    module: 'colegiado',
    roles: ['rait-secretary', 'rait-chair'],
    resolver: 'ata gerada, assinatura, publicação',
    uc: ['UC-RAIT-020'],
    journeys: ['JRN-RAIT-002', 'JRN-RAIT-003', 'JW-04', 'JW-08'],
    level: 'L2',
  },
  {
    path: 'colegiado/:orgao/vistas',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-037',
    module: 'colegiado',
    roles: ['rait-chair', 'rait-rapporteur'],
    resolver: 'itens com vista e prazos',
    uc: ['UC-RAIT-019'],
    journeys: ['JW-08', 'JW-07'],
    level: 'L2',
  },
  {
    path: 'colegiado/:orgao/extraordinaria',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-038',
    module: 'colegiado',
    roles: ['rait-chair'],
    resolver: 'convocação extraordinária',
    uc: ['UC-RAIT-021'],
    journeys: ['JW-08'],
    level: 'L2',
  },
  {
    path: 'gestao',
    kind: 'redirect',
    screen: null,
    sheet: null,
    module: 'gestao',
    roles: ['rait-manager', 'rait-coordinator'],
    resolver: 'raiz de grupo: redireciona ao primeiro filho permitido ao papel',
    uc: [],
    journeys: ['JW-09', 'JW-02'],
    level: null,
  },
  {
    path: 'gestao/radar',
    kind: 'page',
    screen: 'T-14',
    sheet: 'IU-RAIT-039',
    module: 'gestao',
    roles: ['rait-manager'],
    resolver: 'radar de prescrição por relógio',
    uc: ['UC-RAIT-010'],
    journeys: ['JRN-RAIT-004', 'JW-09'],
    level: 'L2',
  },
  {
    path: 'gestao/radar/:caseId',
    kind: 'page',
    screen: 'T-15',
    sheet: 'IU-RAIT-040',
    module: 'gestao',
    roles: ['rait-manager'],
    resolver: 'drill-down e ação (reatribuir, priorizar, escalar)',
    uc: ['UC-RAIT-010', 'UC-RAIT-011'],
    journeys: ['JRN-RAIT-004', 'JW-09'],
    level: 'L2',
  },
  {
    path: 'gestao/producao',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-041',
    module: 'gestao',
    roles: ['rait-manager', 'rait-coordinator'],
    resolver: 'produção, metas, taxa de provimento',
    uc: ['UC-RAIT-040'],
    journeys: ['JRN-RAIT-004', 'JW-09', 'JW-02'],
    level: 'L1',
  },
  {
    path: 'gestao/capacidade',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-042',
    module: 'gestao',
    roles: ['rait-coordinator', 'rait-manager'],
    resolver: 'projeção e plano do período',
    uc: ['UC-RAIT-038'],
    journeys: ['JRN-RAIT-004', 'JW-02', 'JW-09'],
    level: 'L1',
  },
  {
    path: 'gestao/turmas',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-043',
    module: 'gestao',
    roles: ['rait-manager'],
    resolver: 'unidades e constituição',
    uc: ['UC-RAIT-039'],
    journeys: ['JRN-RAIT-004', 'JW-09'],
    level: 'L1',
  },
  {
    path: 'gestao/incidentes',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-044',
    module: 'gestao',
    roles: ['rait-manager'],
    resolver: 'PRESCRITO_OPERACIONAL, extinções declaradas',
    uc: ['UC-RAIT-023'],
    journeys: ['JW-09'],
    level: 'L2',
  },
  {
    path: 'gestao/qualidade',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-045',
    module: 'gestao',
    roles: ['rait-coordinator'],
    resolver: 'amostragem e achados',
    uc: ['UC-RAIT-025'],
    journeys: ['JW-02'],
    level: 'L1',
  },
  {
    path: 'organizacao',
    kind: 'redirect',
    screen: null,
    sheet: null,
    module: 'organizacao',
    roles: ['rait-coordinator', 'rait-chair', 'rait-secretary', 'rait-hr'],
    resolver: 'raiz de grupo: redireciona ao primeiro filho permitido ao papel',
    uc: [],
    journeys: ['JW-02', 'JW-08', 'JW-04', 'JW-10'],
    level: null,
  },
  {
    path: 'organizacao/escala',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-046',
    module: 'organizacao',
    roles: ['rait-coordinator', 'rait-chair'],
    resolver:
      'escala semanal e plantão — §11 linha 4 (escala/plantão pendente)',
    uc: ['UC-RAIT-013'],
    journeys: ['JW-02', 'JW-08'],
    level: 'L0',
  },
  {
    path: 'organizacao/membros',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-047',
    module: 'organizacao',
    roles: ['rait-hr', 'rait-chair'],
    resolver: 'membros, mandatos, posse, perda',
    uc: ['UC-RAIT-037'],
    journeys: ['JW-10', 'JW-08'],
    level: 'L1',
  },
  {
    path: 'organizacao/pools',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-048',
    module: 'organizacao',
    roles: ['rait-coordinator', 'agency-admin'],
    resolver: 'pools e estratégias',
    uc: [],
    journeys: ['JW-02', 'JW-12'],
    level: 'L1',
  },
  {
    path: 'organizacao/jeton',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-049',
    module: 'organizacao',
    roles: ['rait-secretary', 'rait-hr'],
    resolver: 'folha de remuneração por sessão — §11 linha 8 (jeton pendente)',
    uc: ['UC-RAIT-036'],
    journeys: ['JRN-RAIT-003', 'JW-04', 'JW-10'],
    level: 'L0',
  },
  {
    path: 'integracoes',
    kind: 'redirect',
    screen: null,
    sheet: null,
    module: 'integracoes',
    roles: ['integration-operator', 'rait-manager'],
    resolver: 'raiz de grupo: redireciona ao primeiro filho permitido ao papel',
    uc: [],
    journeys: ['JW-11', 'JW-09'],
    level: null,
  },
  {
    path: 'integracoes/renainf',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-050',
    module: 'integracoes',
    roles: ['integration-operator', 'rait-manager'],
    resolver:
      'espelhamento e recibos — §11 linha 6 (painel de integrações pendente)',
    uc: ['UC-RAIT-029'],
    journeys: ['JW-11', 'JW-09'],
    level: 'L0',
  },
  {
    path: 'integracoes/renach',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-051',
    module: 'integracoes',
    roles: ['integration-operator', 'rait-manager'],
    resolver: 'penalidades definitivas e estornos — §11 linha 6',
    uc: ['UC-RAIT-030'],
    journeys: ['JW-11', 'JW-09'],
    level: 'L0',
  },
  {
    path: 'integracoes/falhas',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-052',
    module: 'integracoes',
    roles: ['integration-operator', 'rait-manager'],
    resolver: 'retransmissão e conciliação — §11 linha 6',
    uc: ['UC-RAIT-031'],
    journeys: ['JW-11', 'JW-09'],
    level: 'L0',
  },
  {
    path: 'financeiro',
    kind: 'redirect',
    screen: null,
    sheet: null,
    module: 'financeiro',
    roles: ['rait-finance'],
    resolver: 'raiz de grupo: redireciona ao primeiro filho permitido ao papel',
    uc: [],
    journeys: ['JW-10'],
    level: null,
  },
  {
    path: 'financeiro/arrecadacao',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-053',
    module: 'financeiro',
    roles: ['rait-finance'],
    resolver: 'documentos por fase — §11 linha 5 (módulo financeiro pendente)',
    uc: ['UC-RAIT-032'],
    journeys: ['JW-10'],
    level: 'L0',
  },
  {
    path: 'financeiro/restituicoes',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-054',
    module: 'financeiro',
    roles: ['rait-finance'],
    resolver: 'ordens de restituição — §11 linha 5',
    uc: ['UC-RAIT-033'],
    journeys: ['JW-10'],
    level: 'L0',
  },
  {
    path: 'financeiro/cobranca',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-055',
    module: 'financeiro',
    roles: ['rait-finance'],
    resolver: 'cobrança e dívida ativa — §11 linha 5',
    uc: ['UC-RAIT-034'],
    journeys: ['JW-10'],
    level: 'L0',
  },
  {
    path: 'financeiro/conciliacao',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-056',
    module: 'financeiro',
    roles: ['rait-finance'],
    resolver: 'retornos bancários — §11 linha 5',
    uc: ['UC-RAIT-035'],
    journeys: ['JW-10'],
    level: 'L0',
  },
  {
    path: 'arquivo',
    kind: 'redirect',
    screen: null,
    sheet: null,
    module: 'arquivo',
    roles: ['rait-secretary', 'AUDITOR'],
    resolver: 'raiz de grupo: redireciona ao primeiro filho permitido ao papel',
    uc: [],
    journeys: ['JW-03', 'JW-12'],
    level: null,
  },
  {
    path: 'arquivo/busca',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-057',
    module: 'arquivo',
    roles: ['rait-secretary', 'AUDITOR'],
    resolver: 'autos encerrados',
    uc: ['UC-RAIT-024'],
    journeys: ['JW-03', 'JW-12'],
    level: 'L2',
  },
  {
    path: 'arquivo/casos/:id',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-058',
    module: 'arquivo',
    roles: ['rait-secretary', 'AUDITOR'],
    resolver: 'dossiê final selado, vista/cópia',
    uc: ['UC-RAIT-024'],
    journeys: ['JW-03', 'JW-12'],
    level: 'L2',
  },
  {
    path: 'arquivo/retencao',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-059',
    module: 'arquivo',
    roles: ['rait-secretary'],
    resolver: 'fila de retenção e anonimização',
    uc: ['UC-RAIT-024'],
    journeys: ['JRN-RAIT-003', 'JW-03'],
    level: 'L2',
  },
  {
    path: 'auditoria',
    kind: 'redirect',
    screen: null,
    sheet: null,
    module: 'auditoria',
    roles: ['AUDITOR'],
    resolver: 'raiz de grupo: redireciona ao primeiro filho permitido ao papel',
    uc: [],
    journeys: ['JW-12'],
    level: null,
  },
  {
    path: 'auditoria/trilha',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-060',
    module: 'auditoria',
    roles: ['AUDITOR'],
    resolver: 'trilha por caso/período',
    uc: ['UC-RAIT-042'],
    journeys: ['JW-12'],
    level: 'L2',
  },
  {
    path: 'auditoria/exportacoes',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-061',
    module: 'auditoria',
    roles: ['AUDITOR'],
    resolver:
      'exportações registradas — §11 linha 8 (exportações assinadas pendentes)',
    uc: ['UC-RAIT-042'],
    journeys: ['JW-12'],
    level: 'L0',
  },
  {
    path: 'admin',
    kind: 'redirect',
    screen: null,
    sheet: null,
    module: 'admin',
    roles: ['agency-admin'],
    resolver: 'raiz de grupo: redireciona ao primeiro filho permitido ao papel',
    uc: [],
    journeys: ['JW-12'],
    level: null,
  },
  {
    path: 'admin/parametros',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-062',
    module: 'admin',
    roles: ['agency-admin'],
    resolver:
      'timers operacionais, WIP, lotes, escada — §11 linha 7 (parâmetros versionados pendentes)',
    uc: ['UC-RAIT-043'],
    journeys: ['JW-12'],
    level: 'L0',
  },
  {
    path: 'admin/calendario',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-063',
    module: 'admin',
    roles: ['agency-admin'],
    resolver:
      'feriados nacional + AM — §11 linha 7 (calendário de feriados pendente)',
    uc: [],
    journeys: ['JW-12'],
    level: 'L0',
  },
  {
    path: 'admin/atos/suspensao',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-064',
    module: 'admin',
    roles: ['agency-admin'],
    resolver:
      'atos de força maior — §11 linha 7 (admin pendente); comando `rait-suspension-act:create` "pendente" em §7',
    uc: ['UC-RAIT-022'],
    journeys: ['JW-12'],
    level: 'L0',
  },
  {
    path: 'conta',
    kind: 'page',
    screen: null,
    sheet: 'IU-RAIT-018',
    module: 'conta',
    roles: 'all',
    resolver: 'perfil, papéis ativos, tema',
    uc: [],
    journeys: JW_ALL,
    level: 'L2',
  },
  {
    path: 'sem-permissao',
    kind: 'page',
    screen: null,
    sheet: null,
    module: 'core',
    roles: 'all',
    resolver: 'destino do `roleGuard` (A2); `?de=<url>`',
    uc: [],
    journeys: JW_ALL,
    level: 'L2',
  },
  {
    path: 'auth/callback',
    kind: 'page',
    screen: null,
    sheet: null,
    module: 'core',
    roles: 'all',
    resolver:
      'retorno OIDC (A2; padrão do Portal): `completeLogin` e redirect a `/`',
    uc: [],
    journeys: JW_ALL,
    level: 'L2',
  },
];

/**
 * Tabela A de `route-manifest.md`: `path` → slug de `rait.screens.<slug>.*` (tabela literal, não
 * derivada em runtime; `screenSlugOf` é a regra e o teste C-2A-03 prova que coincidem).
 */
export const RAIT_SCREEN_SLUGS: Readonly<Record<string, string>> = {
  '': 'home',
  painel: 'painel',
  'painel/retomar': 'painel-retomar',
  'fila/defesa': 'fila-defesa',
  'fila/recurso/:orgao': 'fila-recurso-orgao',
  'casos/:id': 'casos-id',
  'casos/:id/resumo': 'casos-id-resumo',
  'casos/:id/triagem': 'casos-id-triagem',
  'casos/:id/dossie': 'casos-id-dossie',
  'casos/:id/diligencias': 'casos-id-diligencias',
  'casos/:id/minuta': 'casos-id-minuta',
  'casos/:id/decisao': 'casos-id-decisao',
  'casos/:id/prazos': 'casos-id-prazos',
  'casos/:id/partes': 'casos-id-partes',
  'casos/:id/comunicacoes': 'casos-id-comunicacoes',
  'casos/:id/impedimentos': 'casos-id-impedimentos',
  'casos/:id/historico': 'casos-id-historico',
  protocolo: 'protocolo',
  'protocolo/novo': 'protocolo-novo',
  'protocolo/pendencias': 'protocolo-pendencias',
  'protocolo/remessas': 'protocolo-remessas',
  'protocolo/redirecionamentos': 'protocolo-redirecionamentos',
  'protocolo/desistencias': 'protocolo-desistencias',
  assinatura: 'assinatura',
  'assinatura/:caseId': 'assinatura-caseId',
  'autoridade/provimentos': 'autoridade-provimentos',
  'colegiado/:orgao': 'colegiado-orgao',
  'colegiado/:orgao/distribuicao': 'colegiado-orgao-distribuicao',
  'colegiado/:orgao/distribuicao/:loteId':
    'colegiado-orgao-distribuicao-loteId',
  'colegiado/:orgao/relatoria': 'colegiado-orgao-relatoria',
  'colegiado/:orgao/relatoria/:caseId/voto':
    'colegiado-orgao-relatoria-caseId-voto',
  'colegiado/:orgao/pauta': 'colegiado-orgao-pauta',
  'colegiado/:orgao/sessoes': 'colegiado-orgao-sessoes',
  'colegiado/:orgao/sessoes/:id': 'colegiado-orgao-sessoes-id',
  'colegiado/:orgao/sessoes/:id/banca': 'colegiado-orgao-sessoes-id-banca',
  'colegiado/:orgao/sessoes/:id/ata': 'colegiado-orgao-sessoes-id-ata',
  'colegiado/:orgao/vistas': 'colegiado-orgao-vistas',
  'colegiado/:orgao/extraordinaria': 'colegiado-orgao-extraordinaria',
  gestao: 'gestao',
  'gestao/radar': 'gestao-radar',
  'gestao/radar/:caseId': 'gestao-radar-caseId',
  'gestao/producao': 'gestao-producao',
  'gestao/capacidade': 'gestao-capacidade',
  'gestao/turmas': 'gestao-turmas',
  'gestao/incidentes': 'gestao-incidentes',
  'gestao/qualidade': 'gestao-qualidade',
  organizacao: 'organizacao',
  'organizacao/escala': 'organizacao-escala',
  'organizacao/membros': 'organizacao-membros',
  'organizacao/pools': 'organizacao-pools',
  'organizacao/jeton': 'organizacao-jeton',
  integracoes: 'integracoes',
  'integracoes/renainf': 'integracoes-renainf',
  'integracoes/renach': 'integracoes-renach',
  'integracoes/falhas': 'integracoes-falhas',
  financeiro: 'financeiro',
  'financeiro/arrecadacao': 'financeiro-arrecadacao',
  'financeiro/restituicoes': 'financeiro-restituicoes',
  'financeiro/cobranca': 'financeiro-cobranca',
  'financeiro/conciliacao': 'financeiro-conciliacao',
  arquivo: 'arquivo',
  'arquivo/busca': 'arquivo-busca',
  'arquivo/casos/:id': 'arquivo-casos-id',
  'arquivo/retencao': 'arquivo-retencao',
  auditoria: 'auditoria',
  'auditoria/trilha': 'auditoria-trilha',
  'auditoria/exportacoes': 'auditoria-exportacoes',
  admin: 'admin',
  'admin/parametros': 'admin-parametros',
  'admin/calendario': 'admin-calendario',
  'admin/atos/suspensao': 'admin-atos-suspensao',
  conta: 'conta',
  'sem-permissao': 'sem-permissao',
  'auth/callback': 'auth-callback',
};

/** Regra da tabela A (puro): `/` → `-`, `:param` → `param`, `''` → `home`. */
export function screenSlugOf(path: string): string {
  return path === '' ? 'home' : path.replace(/:/g, '').replace(/\//g, '-');
}

const SCREENS_NAMESPACE = 'rait.screens';

/** `rait.screens.<slug>.title` — título de janela/breadcrumb da rota. */
export function titleKeyOf(entry: RaitRouteEntry): string {
  return `${SCREENS_NAMESPACE}.${screenSlugOf(entry.path)}.title`;
}

/** Entradas de um módulo, na ordem do manifesto. */
export function manifestEntriesOf(
  module: RaitModule,
): readonly RaitRouteEntry[] {
  return RAIT_ROUTE_MANIFEST.filter((entry) => entry.module === module);
}

/** Entrada pelo `path` exato do manifesto; lança quando ausente (nunca `undefined`). */
export function manifestEntryOf(path: string): RaitRouteEntry {
  const entry = RAIT_ROUTE_MANIFEST.find(
    (candidate) => candidate.path === path,
  );
  if (!entry) {
    throw new Error(`rota fora do manifesto: "${path}"`);
  }
  return entry;
}
