// Espelho tipado das 46 linhas de `inf.infraction_transition_ref`
// (backend/database/ddl/14-inf-lifecycle-vocabulary.sql, bloco INSERT), na ordem
// do `id` e com os mesmos valores — nenhuma reinterpretação
// (work/rounds/R-0006/contracts/CTG-0001.md §3). As linhas `a_confirmar` (27, 38)
// e a linha `nao_modelada` (41) ficam na tabela para que a matriz seja auditável
// contra o DDL; a resolução as filtra (§3.2).
/** `inf.infraction_transition_ref.trigger_kind`. */
export type InfractionTriggerKind = 'evento' | 'timer' | 'ato' | 'sistema';

export interface InfractionTransition {
  /** `inf.infraction_transition_ref.id` (1..46). */
  id: number;
  /** `rule_ref` = número da linha de [WF-INF-003] §2 (1..31). */
  ruleRef: number;
  fromState: string | null;
  fromSubstate: string | null;
  toState: string;
  toSubstate: string | null;
  triggerKind: InfractionTriggerKind;
  triggerCode: string;
  status: 'vigente' | 'a_confirmar' | 'nao_modelada';
  legalBasis: string;
}

export const INFRACTION_TRANSITIONS: readonly InfractionTransition[] = [
  {
    id: 1,
    ruleRef: 1,
    fromState: null,
    fromSubstate: null,
    toState: 'AIT_LAVRADO',
    toSubstate: null,
    triggerKind: 'evento',
    triggerCode: 'AIT_INTEGRADO',
    status: 'vigente',
    legalBasis: 'CTB art. 281',
  },
  {
    id: 2,
    ruleRef: 2,
    fromState: 'AIT_LAVRADO',
    fromSubstate: null,
    toState: 'ARQUIVADO',
    toSubstate: null,
    triggerKind: 'ato',
    triggerCode: 'AUTORIDADE_JULGA_INSUBSISTENTE',
    status: 'vigente',
    legalBasis: 'CTB art. 281 §1º I',
  },
  {
    id: 3,
    ruleRef: 3,
    fromState: 'AIT_LAVRADO',
    fromSubstate: null,
    toState: 'ARQUIVADO',
    toSubstate: null,
    triggerKind: 'timer',
    triggerCode: 'T-NA',
    status: 'vigente',
    legalBasis: 'Res. 918/2022 art. 4º §1º',
  },
  {
    id: 4,
    ruleRef: 4,
    fromState: 'AIT_LAVRADO',
    fromSubstate: null,
    toState: 'NOTIFICADO_AUTUACAO',
    toSubstate: 'PRAZO_DEFESA_ABERTO',
    triggerKind: 'evento',
    triggerCode: 'NOTIFICACAO_EXPEDIDA(NA)',
    status: 'vigente',
    legalBasis: 'Res. 918/2022 arts. 3º §5º, 4º',
  },
  {
    id: 5,
    ruleRef: 5,
    fromState: 'NOTIFICADO_AUTUACAO',
    fromSubstate: 'PRAZO_DEFESA_ABERTO',
    toState: 'NOTIFICADO_AUTUACAO',
    toSubstate: 'INDICACAO_EM_PROCESSAMENTO',
    triggerKind: 'evento',
    triggerCode: 'CONDUTOR_INDICADO',
    status: 'vigente',
    legalBasis: 'Res. 918/2022 art. 5º',
  },
  {
    id: 6,
    ruleRef: 5,
    fromState: 'NOTIFICADO_AUTUACAO',
    fromSubstate: 'INDICACAO_EM_PROCESSAMENTO',
    toState: 'NOTIFICADO_AUTUACAO',
    toSubstate: 'PRAZO_DEFESA_ABERTO',
    triggerKind: 'sistema',
    triggerCode: 'INDICACAO_VALIDADA',
    status: 'vigente',
    legalBasis: 'Res. 918/2022 arts. 5º-6º',
  },
  {
    id: 7,
    ruleRef: 6,
    fromState: 'NOTIFICADO_AUTUACAO',
    fromSubstate: null,
    toState: 'DEFESA_EM_JULGAMENTO',
    toSubstate: null,
    triggerKind: 'evento',
    triggerCode: 'RAIT_CASO_PROTOCOLADO(defesa_previa)',
    status: 'vigente',
    legalBasis: 'Res. 918/2022 art. 9º',
  },
  {
    id: 8,
    ruleRef: 7,
    fromState: 'NOTIFICADO_AUTUACAO',
    fromSubstate: null,
    toState: 'PENALIDADE_A_APLICAR',
    toSubstate: null,
    triggerKind: 'timer',
    triggerCode: 'T-DEF',
    status: 'vigente',
    legalBasis: 'Res. 918/2022 art. 9º §2º; CTB art. 257 §8º',
  },
  {
    id: 9,
    ruleRef: 8,
    fromState: 'DEFESA_EM_JULGAMENTO',
    fromSubstate: null,
    toState: 'AIT_CANCELADO',
    toSubstate: null,
    triggerKind: 'evento',
    triggerCode: 'RAIT_DECISAO_PUBLICADA(acolhida)',
    status: 'vigente',
    legalBasis: 'Res. 918/2022 art. 9º §1º',
  },
  {
    id: 10,
    ruleRef: 9,
    fromState: 'DEFESA_EM_JULGAMENTO',
    fromSubstate: null,
    toState: 'PENALIDADE_A_APLICAR',
    toSubstate: null,
    triggerKind: 'evento',
    triggerCode:
      'RAIT_DECISAO_PUBLICADA(indeferida|nao_conhecido) | ENCERRADO_DESISTENCIA',
    status: 'vigente',
    legalBasis: 'Res. 918/2022 art. 9º §2º; Res. 900/2022 art. 11',
  },
  {
    id: 11,
    ruleRef: 10,
    fromState: 'DEFESA_EM_JULGAMENTO',
    fromSubstate: null,
    toState: 'EXTINTO_DECADENCIA',
    toSubstate: null,
    triggerKind: 'timer',
    triggerCode: 'T-DEC',
    status: 'vigente',
    legalBasis: 'CTB art. 282 §7º',
  },
  {
    id: 12,
    ruleRef: 10,
    fromState: 'PENALIDADE_A_APLICAR',
    fromSubstate: null,
    toState: 'EXTINTO_DECADENCIA',
    toSubstate: null,
    triggerKind: 'timer',
    triggerCode: 'T-DEC',
    status: 'vigente',
    legalBasis: 'CTB art. 282 §7º',
  },
  {
    id: 13,
    ruleRef: 11,
    fromState: 'PENALIDADE_A_APLICAR',
    fromSubstate: null,
    toState: 'NOTIFICADO_PENALIDADE',
    toSubstate: null,
    triggerKind: 'evento',
    triggerCode: 'NOTIFICACAO_EXPEDIDA(NP)',
    status: 'vigente',
    legalBasis: 'CTB art. 282; Res. 918/2022 art. 12',
  },
  {
    id: 14,
    ruleRef: 12,
    fromState: 'PENALIDADE_A_APLICAR',
    fromSubstate: null,
    toState: 'INSTANCIA_ENCERRADA',
    toSubstate: 'QUITADA',
    triggerKind: 'evento',
    triggerCode: 'NOTIFICACAO_EXPEDIDA(NP, reconhecimento=true)',
    status: 'vigente',
    legalBasis: 'CTB arts. 284 §1º, 290 III',
  },
  {
    id: 15,
    ruleRef: 13,
    fromState: 'NOTIFICADO_PENALIDADE',
    fromSubstate: null,
    toState: 'NOTIFICADO_PENALIDADE',
    toSubstate: null,
    triggerKind: 'evento',
    triggerCode: 'PAGAMENTO_CONFIRMADO',
    status: 'vigente',
    legalBasis: 'CTB art. 284 §2º',
  },
  {
    id: 16,
    ruleRef: 14,
    fromState: 'NOTIFICADO_PENALIDADE',
    fromSubstate: null,
    toState: 'RECURSO_1A_INSTANCIA',
    toSubstate: 'EM_ADMISSIBILIDADE_1A',
    triggerKind: 'evento',
    triggerCode: 'RAIT_CASO_PROTOCOLADO(jari)',
    status: 'vigente',
    legalBasis: 'CTB art. 285',
  },
  {
    id: 17,
    ruleRef: 15,
    fromState: 'NOTIFICADO_PENALIDADE',
    fromSubstate: null,
    toState: 'INSTANCIA_ENCERRADA',
    toSubstate: 'PENDENTE_PAGAMENTO',
    triggerKind: 'timer',
    triggerCode: 'T-NP-VENC',
    status: 'vigente',
    legalBasis: 'CTB art. 290 II',
  },
  {
    id: 18,
    ruleRef: 16,
    fromState: 'NOTIFICADO_PENALIDADE',
    fromSubstate: null,
    toState: 'INSTANCIA_ENCERRADA',
    toSubstate: 'QUITADA',
    triggerKind: 'evento',
    triggerCode:
      'PAGAMENTO_CONFIRMADO(reconhecimento) + REQUERIMENTO_ENCERRAMENTO',
    status: 'vigente',
    legalBasis: 'CTB art. 290 III',
  },
  {
    id: 19,
    ruleRef: 17,
    fromState: 'RECURSO_1A_INSTANCIA',
    fromSubstate: 'EM_ADMISSIBILIDADE_1A',
    toState: 'RECURSO_1A_INSTANCIA',
    toSubstate: 'EM_REMESSA_JARI',
    triggerKind: 'evento',
    triggerCode: 'RAIT_EFEITO_SUSPENSIVO_INSTAURADO',
    status: 'vigente',
    legalBasis: 'CTB art. 285 caput e §1º; RN-RAIT-108',
  },
  {
    id: 20,
    ruleRef: 18,
    fromState: 'RECURSO_1A_INSTANCIA',
    fromSubstate: 'EM_REMESSA_JARI',
    toState: 'RECURSO_1A_INSTANCIA',
    toSubstate: 'EM_JULGAMENTO_JARI',
    triggerKind: 'evento',
    triggerCode: 'RAIT_RECURSO_RECEBIDO_JULGADOR',
    status: 'vigente',
    legalBasis: 'CTB art. 285 §§2º, 6º',
  },
  {
    id: 21,
    ruleRef: 19,
    fromState: 'RECURSO_1A_INSTANCIA',
    fromSubstate: null,
    toState: 'NOTIFICADO_PENALIDADE',
    toSubstate: null,
    triggerKind: 'evento',
    triggerCode: 'RAIT_DECISAO_PUBLICADA(nao_conhecido) na triagem',
    status: 'vigente',
    legalBasis: 'CTB art. 285 §5º',
  },
  {
    id: 22,
    ruleRef: 19,
    fromState: 'RECURSO_1A_INSTANCIA',
    fromSubstate: null,
    toState: 'INSTANCIA_ENCERRADA',
    toSubstate: 'PENDENTE_PAGAMENTO',
    triggerKind: 'evento',
    triggerCode: 'RAIT_DECISAO_PUBLICADA(nao_conhecido) na triagem',
    status: 'vigente',
    legalBasis: 'CTB arts. 285 §5º, 290 II',
  },
  {
    id: 23,
    ruleRef: 20,
    fromState: 'RECURSO_1A_INSTANCIA',
    fromSubstate: null,
    toState: 'NOTIFICADO_PENALIDADE',
    toSubstate: null,
    triggerKind: 'evento',
    triggerCode: 'ENCERRADO_DESISTENCIA',
    status: 'vigente',
    legalBasis: 'RN-RAIT-123',
  },
  {
    id: 24,
    ruleRef: 20,
    fromState: 'RECURSO_1A_INSTANCIA',
    fromSubstate: null,
    toState: 'INSTANCIA_ENCERRADA',
    toSubstate: 'PENDENTE_PAGAMENTO',
    triggerKind: 'evento',
    triggerCode: 'ENCERRADO_DESISTENCIA',
    status: 'vigente',
    legalBasis: 'RN-RAIT-123; CTB art. 290 II',
  },
  {
    id: 25,
    ruleRef: 21,
    fromState: 'RECURSO_1A_INSTANCIA',
    fromSubstate: null,
    toState: 'AGUARDANDO_RECURSO_2A',
    toSubstate: null,
    triggerKind: 'evento',
    triggerCode: 'RAIT_DECISAO_PUBLICADA (JARI)',
    status: 'vigente',
    legalBasis: 'CTB art. 288',
  },
  {
    id: 26,
    ruleRef: 22,
    fromState: 'RECURSO_1A_INSTANCIA',
    fromSubstate: null,
    toState: 'EXTINTO_PRESCRICAO',
    toSubstate: null,
    triggerKind: 'timer',
    triggerCode: 'T-JUL-24M',
    status: 'vigente',
    legalBasis: 'CTB art. 289-A',
  },
  {
    id: 27,
    ruleRef: 22,
    fromState: 'RECURSO_1A_INSTANCIA',
    fromSubstate: null,
    toState: 'EXTINTO_PRESCRICAO',
    toSubstate: null,
    triggerKind: 'timer',
    triggerCode: 'T-PAR-3A',
    status: 'a_confirmar',
    legalBasis: 'Lei 9.873/1999 art. 1º §1º',
  },
  {
    id: 28,
    ruleRef: 23,
    fromState: 'AGUARDANDO_RECURSO_2A',
    fromSubstate: 'PROVIDO_1A',
    toState: 'RECURSO_2A_INSTANCIA',
    toSubstate: 'EM_JULGAMENTO_CETRAN',
    triggerKind: 'ato',
    triggerCode: 'RECURSO_AUTORIDADE',
    status: 'vigente',
    legalBasis: 'CTB art. 288 §1º; RN-RAIT-130',
  },
  {
    id: 29,
    ruleRef: 24,
    fromState: 'AGUARDANDO_RECURSO_2A',
    fromSubstate: 'PROVIDO_1A',
    toState: 'CANCELADO_DEFINITIVO',
    toSubstate: null,
    triggerKind: 'timer',
    triggerCode: 'T-R2',
    status: 'vigente',
    legalBasis: 'CTB arts. 286 §2º, 288',
  },
  {
    id: 30,
    ruleRef: 25,
    fromState: 'AGUARDANDO_RECURSO_2A',
    fromSubstate: 'NEGADO_1A',
    toState: 'RECURSO_2A_INSTANCIA',
    toSubstate: 'EM_ADMISSIBILIDADE_2A',
    triggerKind: 'evento',
    triggerCode: 'RAIT_CASO_PROTOCOLADO(cetran)',
    status: 'vigente',
    legalBasis: 'CTB art. 288 caput',
  },
  {
    id: 31,
    ruleRef: 26,
    fromState: 'AGUARDANDO_RECURSO_2A',
    fromSubstate: 'NEGADO_1A',
    toState: 'INSTANCIA_ENCERRADA',
    toSubstate: 'PENDENTE_PAGAMENTO',
    triggerKind: 'timer',
    triggerCode: 'T-R2',
    status: 'vigente',
    legalBasis: 'CTB art. 290 II',
  },
  {
    id: 32,
    ruleRef: 18,
    fromState: 'RECURSO_2A_INSTANCIA',
    fromSubstate: 'EM_ADMISSIBILIDADE_2A',
    toState: 'RECURSO_2A_INSTANCIA',
    toSubstate: 'EM_JULGAMENTO_CETRAN',
    triggerKind: 'evento',
    triggerCode: 'RAIT_RECURSO_RECEBIDO_JULGADOR',
    status: 'vigente',
    legalBasis: 'CTB art. 289; RN-RAIT-111',
  },
  {
    id: 33,
    ruleRef: 27,
    fromState: 'RECURSO_2A_INSTANCIA',
    fromSubstate: null,
    toState: 'INSTANCIA_ENCERRADA',
    toSubstate: 'PENDENTE_PAGAMENTO',
    triggerKind: 'evento',
    triggerCode: 'RAIT_CASO_TRANSITADO (penalidade mantida)',
    status: 'vigente',
    legalBasis: 'CTB art. 290 I',
  },
  {
    id: 34,
    ruleRef: 27,
    fromState: 'RECURSO_2A_INSTANCIA',
    fromSubstate: null,
    toState: 'AGUARDANDO_RECURSO_2A',
    toSubstate: 'NEGADO_1A',
    triggerKind: 'evento',
    triggerCode:
      'RAIT_DECISAO_PUBLICADA(nao_conhecido) | ENCERRADO_DESISTENCIA',
    status: 'vigente',
    legalBasis: 'CTB art. 288',
  },
  {
    id: 35,
    ruleRef: 27,
    fromState: 'RECURSO_2A_INSTANCIA',
    fromSubstate: null,
    toState: 'INSTANCIA_ENCERRADA',
    toSubstate: 'PENDENTE_PAGAMENTO',
    triggerKind: 'evento',
    triggerCode:
      'RAIT_DECISAO_PUBLICADA(nao_conhecido) | ENCERRADO_DESISTENCIA',
    status: 'vigente',
    legalBasis: 'CTB art. 290 II',
  },
  {
    id: 36,
    ruleRef: 28,
    fromState: 'RECURSO_2A_INSTANCIA',
    fromSubstate: null,
    toState: 'CANCELADO_DEFINITIVO',
    toSubstate: null,
    triggerKind: 'evento',
    triggerCode: 'RAIT_CASO_TRANSITADO (favorável)',
    status: 'vigente',
    legalBasis: 'CTB art. 286 §2º',
  },
  {
    id: 37,
    ruleRef: 22,
    fromState: 'RECURSO_2A_INSTANCIA',
    fromSubstate: null,
    toState: 'EXTINTO_PRESCRICAO',
    toSubstate: null,
    triggerKind: 'timer',
    triggerCode: 'T-JUL-24M',
    status: 'vigente',
    legalBasis: 'CTB art. 289-A',
  },
  {
    id: 38,
    ruleRef: 22,
    fromState: 'RECURSO_2A_INSTANCIA',
    fromSubstate: null,
    toState: 'EXTINTO_PRESCRICAO',
    toSubstate: null,
    triggerKind: 'timer',
    triggerCode: 'T-PAR-3A',
    status: 'a_confirmar',
    legalBasis: 'Lei 9.873/1999 art. 1º §1º',
  },
  {
    id: 39,
    ruleRef: 29,
    fromState: 'INSTANCIA_ENCERRADA',
    fromSubstate: 'PENDENTE_PAGAMENTO',
    toState: 'INSTANCIA_ENCERRADA',
    toSubstate: 'QUITADA',
    triggerKind: 'evento',
    triggerCode: 'PAGAMENTO_CONFIRMADO',
    status: 'vigente',
    legalBasis: 'CTB art. 290; Res. 918/2022 arts. 18, 23',
  },
  {
    id: 40,
    ruleRef: 29,
    fromState: 'INSTANCIA_ENCERRADA',
    fromSubstate: 'PENDENTE_PAGAMENTO',
    toState: 'INSTANCIA_ENCERRADA',
    toSubstate: 'EM_COBRANCA',
    triggerKind: 'sistema',
    triggerCode: 'HANDOFF_DIVIDA_ATIVA',
    status: 'vigente',
    legalBasis: 'UC-RAIT-034',
  },
  {
    id: 41,
    ruleRef: 30,
    fromState: 'INSTANCIA_ENCERRADA',
    fromSubstate: null,
    toState: 'INSTANCIA_ENCERRADA',
    toSubstate: null,
    triggerKind: 'ato',
    triggerCode: 'REVISAO_POS_ENCERRAMENTO',
    status: 'nao_modelada',
    legalBasis: 'Owner C.22',
  },
  {
    id: 42,
    ruleRef: 31,
    fromState: 'AIT_LAVRADO',
    fromSubstate: null,
    toState: 'CANCELADO_POS_INTEGRACAO',
    toSubstate: null,
    triggerKind: 'evento',
    triggerCode: 'AIT_CANCELADO_POSFINAL',
    status: 'vigente',
    legalBasis: 'RN-TEAT-121',
  },
  {
    id: 43,
    ruleRef: 31,
    fromState: 'NOTIFICADO_AUTUACAO',
    fromSubstate: null,
    toState: 'CANCELADO_POS_INTEGRACAO',
    toSubstate: null,
    triggerKind: 'evento',
    triggerCode: 'AIT_CANCELADO_POSFINAL',
    status: 'vigente',
    legalBasis: 'RN-TEAT-121',
  },
  {
    id: 44,
    ruleRef: 31,
    fromState: 'DEFESA_EM_JULGAMENTO',
    fromSubstate: null,
    toState: 'CANCELADO_POS_INTEGRACAO',
    toSubstate: null,
    triggerKind: 'evento',
    triggerCode: 'AIT_CANCELADO_POSFINAL',
    status: 'vigente',
    legalBasis: 'RN-TEAT-121',
  },
  {
    id: 45,
    ruleRef: 31,
    fromState: 'PENALIDADE_A_APLICAR',
    fromSubstate: null,
    toState: 'CANCELADO_POS_INTEGRACAO',
    toSubstate: null,
    triggerKind: 'evento',
    triggerCode: 'AIT_CANCELADO_POSFINAL',
    status: 'vigente',
    legalBasis: 'RN-TEAT-121',
  },
  {
    id: 46,
    ruleRef: 31,
    fromState: 'NOTIFICADO_PENALIDADE',
    fromSubstate: null,
    toState: 'CANCELADO_POS_INTEGRACAO',
    toSubstate: null,
    triggerKind: 'evento',
    triggerCode: 'AIT_CANCELADO_POSFINAL',
    status: 'vigente',
    legalBasis: 'RN-TEAT-121',
  },
];

/**
 * Estados com `inf.infraction_state_ref.is_terminal = true` (DDL 14): nenhum
 * gatilho é admitido sobre eles (CTG-0001 §4, precedência 1).
 */
export const INFRACTION_TERMINAL_STATES: readonly string[] = [
  'INSTANCIA_ENCERRADA',
  'ARQUIVADO',
  'CANCELADO_POS_INTEGRACAO',
  'AIT_CANCELADO',
  'EXTINTO_DECADENCIA',
  'EXTINTO_PRESCRICAO',
  'CANCELADO_DEFINITIVO',
];

/**
 * Únicos gatilhos admitidos em `INSTANCIA_ENCERRADA` — as linhas 39 e 40; todo
 * o resto é `RAIT.INFRACTION_CLOSED_NO_REVISION` (Owner C.22; CTG-0001 §4).
 */
export const INFRACTION_CLOSED_TRIGGERS: readonly string[] = [
  'PAGAMENTO_CONFIRMADO',
  'HANDOFF_DIVIDA_ATIVA',
];

/**
 * Discriminantes por linha, quando `(from_state, from_substate, trigger_kind,
 * trigger_code)` não basta. Os tokens vêm do próprio `trigger_code` do DDL 14
 * (o que está entre parênteses) e de CTG-0001 §3.1/§6.1:
 *
 * - `kind` do aviso: `NA` (4), `NP` (13) e `reconhecimento` (14, "NP,
 *   reconhecimento=true");
 * - `instance` do caso: `defesa_previa` (7), `jari` (16), `cetran` (30);
 * - `decisionKind`: `acolhida` (9), `indeferida`/`nao_conhecido` (10),
 *   `provido`/`negado` (25, sub-estado PROVIDO_1A|NEGADO_1A conforme o
 *   resultado), `negado`/`nao_conhecido` (33) e `provido` (36);
 * - `reconhecimento` (18, "PAGAMENTO_CONFIRMADO(reconhecimento) +
 *   REQUERIMENTO_ENCERRAMENTO"), ausente na linha 15;
 * - estado do prazo nas duplas 21/22, 23/24 e 34/35 — `prazo_aberto` |
 *   `prazo_vencido` —, que não é derivável de `(state, substate, trigger)` e o
 *   chamador determina com `timeliness` do motor de prazos (§6.1).
 *
 * Linha sem entrada aqui casa qualquer gatilho sem `qualifier`.
 */
export const INFRACTION_TRANSITION_QUALIFIERS: Readonly<
  Record<number, readonly string[]>
> = {
  4: ['NA'],
  7: ['defesa_previa'],
  9: ['acolhida'],
  10: ['indeferida', 'nao_conhecido'],
  13: ['NP'],
  14: ['reconhecimento'],
  16: ['jari'],
  18: ['reconhecimento'],
  21: ['prazo_aberto'],
  22: ['prazo_vencido'],
  23: ['prazo_aberto'],
  24: ['prazo_vencido'],
  25: ['provido', 'negado'],
  30: ['cetran'],
  33: ['negado', 'nao_conhecido'],
  34: ['prazo_aberto'],
  35: ['prazo_vencido'],
  36: ['provido'],
};
