// Códigos do catálogo de erros (`docs/framework/arch/rait-error-catalog.md` §3, na ordem de
// aparição; contrato CTG-0002a §8) e a fórmula do catálogo §5.3 para a chave i18n
// (`rait.errors.<código em minúsculas sem prefixo>`). O contrato cita 132 códigos; o catálogo tem
// 131 únicos (adenda A5 b) — a comparação com o catálogo é por conjunto.

export const RAIT_ERROR_PREFIX = 'RAIT.';

const ERRORS_NAMESPACE = 'rait.errors';

export const RAIT_ERROR_CODES = [
  // §3.1 Sessão, permissão e tenant
  'RAIT.AUTH_REQUIRED',
  'RAIT.FORBIDDEN_ACTION',
  'RAIT.FORBIDDEN_CASE_SCOPE',
  'RAIT.FORBIDDEN_ORGAO',
  'RAIT.TENANT_MISMATCH',
  // §3.2 Forma dos payloads
  'RAIT.VALIDATION_FAILED',
  'RAIT.ENUM_INVALID',
  'RAIT.DOCUMENT_INVALID',
  'RAIT.DATE_IN_FUTURE',
  'RAIT.FILE_TYPE_UNSUPPORTED',
  'RAIT.FILE_TOO_LARGE',
  'RAIT.IF_MATCH_REQUIRED',
  'RAIT.VERSION_CONFLICT',
  'RAIT.IDEMPOTENCY_REPLAY',
  // §3.3 Protocolo e intake (`rait-case:protocol`, pendências, redirecionamento, desistência)
  'RAIT.INTAKE_MULTIPLE_AIT',
  'RAIT.INTAKE_DUPLICATE_INSTANCE',
  'RAIT.INTAKE_INFRACTION_STATE_INVALID',
  'RAIT.INTAKE_CHANNEL_MARK_MISSING',
  'RAIT.INTAKE_SIGNATURE_MISSING',
  'RAIT.INTAKE_MINIMUM_CONTENT',
  'RAIT.PENDING_CONTENT_EXPIRED',
  'RAIT.REDIRECT_SAME_BODY',
  'RAIT.WITHDRAWAL_AFTER_DECISION',
  'RAIT.WITHDRAWAL_LEGITIMACY',
  'RAIT.PARTY_LEGITIMACY_INVALID',
  'RAIT.PROCURATION_UNVERIFIED',
  // §3.4 Fila, distribuição e atribuição
  'RAIT.QUEUE_EMPTY',
  'RAIT.ASSIGNMENT_WIP_LIMIT',
  'RAIT.MEMBER_NOT_AVAILABLE',
  'RAIT.MEMBER_IMPEDED',
  'RAIT.ASSIGNMENT_ALREADY_ACTIVE',
  'RAIT.REASSIGN_REASON_REQUIRED',
  'RAIT.REASSIGN_TO_SAME_MEMBER',
  'RAIT.ORDER_OVERRIDE_FORBIDDEN',
  'RAIT.BATCH_STATE_INVALID',
  'RAIT.BATCH_NO_ELIGIBLE_MEMBERS',
  'RAIT.BATCH_SEED_TAMPERED',
  'RAIT.BATCH_CLAIM_EXPIRED',
  'RAIT.SCHEDULE_NO_DUTY_MEMBER',
  'RAIT.SCHEDULE_PERIOD_LOCKED',
  // §3.5 Caso: triagem, instrução, diligência, minuta
  'RAIT.CASE_STATE_INVALID',
  'RAIT.TRIAGE_INCOMPLETE',
  'RAIT.TRIAGE_TIMELINESS_READONLY',
  'RAIT.NON_ADMISSION_REASON_REQUIRED',
  'RAIT.INQUIRY_ADDRESSEE_FORBIDDEN',
  'RAIT.INQUIRY_EXTENSION_LIMIT',
  'RAIT.INQUIRY_ALREADY_CLOSED',
  'RAIT.DRAFT_INCOMPLETE',
  'RAIT.DRAFT_AUTHOR_CANNOT_SIGN',
  'RAIT.DRAFT_RETURN_LIMIT',
  'RAIT.CASE_OFFICIAL_DOCUMENT_REQUIRED',
  'RAIT.DOCUMENT_HASH_MISMATCH',
  // §3.6 Decisão e assinatura
  'RAIT.DECISION_JURISDICTION',
  'RAIT.DECISION_NOT_ON_DUTY',
  'RAIT.DECISION_GROUNDS_REQUIRED',
  'RAIT.DECISION_KIND_INVALID_FOR_INSTANCE',
  'RAIT.SIGNATURE_FAILED',
  'RAIT.SIGNATURE_CERT_MISMATCH',
  'RAIT.DECISION_ALREADY_SIGNED',
  'RAIT.EXTINCTION_CEILING_NOT_REACHED',
  'RAIT.EXTINCTION_DECISION_LATE',
  // §3.7 Colegiado: pauta, sessão, votação, ata, vista
  'RAIT.SESSION_STATE_INVALID',
  'RAIT.AGENDA_ITEM_WITHOUT_OPINION',
  'RAIT.AGENDA_CRITICAL_MISSING',
  'RAIT.AGENDA_SHORT_NOTICE',
  'RAIT.AGENDA_ITEM_DUPLICATE',
  'RAIT.SESSION_QUORUM_MISSING',
  'RAIT.BENCH_INSUFFICIENT',
  'RAIT.VOTE_MEMBER_IMPEDED',
  'RAIT.VOTE_ITEM_NOT_OPEN',
  'RAIT.VOTE_DUPLICATE',
  'RAIT.CASTING_VOTE_NOT_TIED',
  'RAIT.CASTING_VOTE_NOT_CHAIR',
  'RAIT.PROCLAIM_NO_MAJORITY',
  'RAIT.VIEW_REQUEST_NOT_ALLOWED',
  'RAIT.VIEW_DEADLINE_EXCEEDED',
  'RAIT.ORAL_ARGUMENT_DISABLED',
  'RAIT.MINUTES_NOT_READY',
  'RAIT.MINUTES_SIGNERS_MISSING',
  'RAIT.MINUTES_ALREADY_PUBLISHED',
  'RAIT.EXTRAORDINARY_NO_CRITICAL',
  'RAIT.SESSION_PAID_CAP_REACHED',
  // §3.8 Recurso da autoridade, remessa e recebimento
  'RAIT.REMIT_NOT_ADMITTED',
  'RAIT.REMIT_CHECKLIST_INCOMPLETE',
  'RAIT.RECEIPT_ALREADY_REGISTERED',
  'RAIT.AUTHORITY_APPEAL_WINDOW_CLOSED',
  'RAIT.AUTHORITY_APPEAL_NOT_PROVIDED',
  'RAIT.AUTHORITY_APPEAL_ALREADY_DECIDED',
  // §3.9 Prazos, relógios, suspensão e parâmetros
  'RAIT.DEADLINE_LEGAL_READONLY',
  'RAIT.PARAMETER_LEGAL_READONLY',
  'RAIT.PARAMETER_EFFECTIVE_DATE_PAST',
  'RAIT.PARAMETER_SOURCE_PENDING',
  'RAIT.SUSPENSION_LEGAL_TIMER',
  'RAIT.SUSPENSION_EVIDENCE_REQUIRED',
  'RAIT.CLOCK_ALERT_ALREADY_ACKNOWLEDGED',
  'RAIT.CLOCK_ALERT_ROLE_MISMATCH',
  'RAIT.CALENDAR_OVERLAP',
  // §3.10 Organização: membros, mandatos, turmas, jeton
  'RAIT.MANDATE_ACT_REQUIRED',
  'RAIT.MANDATE_DUAL_BODY',
  'RAIT.MANDATE_OVERLAP',
  'RAIT.MANDATE_ACTIVE_ASSIGNMENTS',
  'RAIT.POOL_STRATEGY_INVALID',
  'RAIT.POOL_INSTANCE_DUPLICATE',
  'RAIT.UNIT_COORDINATOR_REQUIRED',
  'RAIT.UNIT_TRIGGER_NOT_MET',
  'RAIT.JETON_MINUTES_UNSIGNED',
  'RAIT.JETON_ALREADY_APPROVED',
  // §3.11 Integrações, financeiro, arquivo e auditoria
  'RAIT.UPSTREAM_RENAINF_UNAVAILABLE',
  'RAIT.UPSTREAM_RENACH_UNAVAILABLE',
  'RAIT.UPSTREAM_SNE_UNAVAILABLE',
  'RAIT.UPSTREAM_REJECTED',
  'RAIT.RECONCILIATION_DIVERGENCE',
  'RAIT.RETRY_NOT_FAILED',
  'RAIT.COLLECTION_PHASE_INVALID',
  'RAIT.COLLECTION_DISCOUNT_SNE_ONLY',
  'RAIT.REFUND_NOT_DUE',
  'RAIT.REFUND_BANK_DATA_MISSING',
  'RAIT.REFUND_INDEX_PENDING',
  'RAIT.DEBT_HANDOFF_NOT_FINAL',
  'RAIT.PAYMENT_UNMATCHED',
  'RAIT.ARCHIVE_NOT_CLOSED',
  'RAIT.ARCHIVE_SEAL_MISMATCH',
  'RAIT.RETENTION_NOT_DUE',
  'RAIT.EXPORT_PURPOSE_REQUIRED',
  'RAIT.EXPORT_DPO_APPROVAL_REQUIRED',
  'RAIT.AUDIT_RANGE_TOO_WIDE',
  // §3.12 Infração (agregado `WF-INF-003`, endpoints do módulo pendente)
  'RAIT.INFRACTION_STATE_INVALID',
  'RAIT.INFRACTION_TIMER_EXPIRED',
  'RAIT.INFRACTION_NOTICE_DEADLINE_SHORT',
  'RAIT.INFRACTION_CLOSED_NO_REVISION',
  'RAIT.INFRACTION_TERMINAL',
] as const;

export type RaitErrorCode = (typeof RAIT_ERROR_CODES)[number];

const KNOWN_CODES: ReadonlySet<string> = new Set(RAIT_ERROR_CODES);

export function isRaitErrorCode(value: unknown): value is RaitErrorCode {
  return typeof value === 'string' && KNOWN_CODES.has(value);
}

/** `RAIT.CASE_STATE_INVALID` → `rait.errors.case_state_invalid` (catálogo §5.3). */
export function messageKeyFor(code: string): string {
  const bare = code.startsWith(RAIT_ERROR_PREFIX)
    ? code.slice(RAIT_ERROR_PREFIX.length)
    : code;
  return `${ERRORS_NAMESPACE}.${bare.toLowerCase()}`;
}
