CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS tenancy;
CREATE SCHEMA IF NOT EXISTS audit;
CREATE SCHEMA IF NOT EXISTS storage;
CREATE SCHEMA IF NOT EXISTS integration;

CREATE SCHEMA IF NOT EXISTS inf;
CREATE SCHEMA IF NOT EXISTS est;
CREATE SCHEMA IF NOT EXISTS ch;
CREATE SCHEMA IF NOT EXISTS ops;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'role_app_backend') THEN
    CREATE ROLE role_app_backend NOLOGIN NOINHERIT NOSUPERUSER NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'role_auditor_min') THEN
    CREATE ROLE role_auditor_min NOLOGIN NOINHERIT NOSUPERUSER NOBYPASSRLS;
  END IF;
END
$$;
