// Os 52 códigos de `dashboard-error-catalog.md` §1–§6, com prefixo, na ordem do catálogo, e a
// fórmula da chave de mensagem (M5; catálogo §7). Nenhum texto aqui: só token → chave.
export const DASH_ERROR_PREFIX = 'DASH.';

export const DASH_ERROR_CODES = [
  // §1 alertas
  'DASH.ALERT_STATE_INVALID',
  'DASH.ALERT_ACK_NOT_OWNER',
  'DASH.ALERT_ACK_MANUAL_NOTE_REQUIRED',
  'DASH.ALERT_CLOSE_WITHOUT_VERIFICATION',
  'DASH.ALERT_EXTINCTION_NOT_CLOSABLE',
  'DASH.ALERT_BUSINESS_ACT_FORBIDDEN',
  'DASH.ALERT_SOURCE_STALE',
  'DASH.ALERT_INCIDENT_NOT_FOUND',
  'DASH.ROOT_CAUSE_CATEGORY_INVALID',
  // §2 deveres
  'DASH.DUTY_STATE_INVALID',
  'DASH.DUTY_EVIDENCE_REQUIRED',
  'DASH.DUTY_EVIDENCE_HASH_INVALID',
  'DASH.DUTY_PERIOD_INVALID',
  'DASH.DUTY_NO_LEGAL_DEADLINE',
  'DASH.DUTY_NOT_OWNER',
  'DASH.DUTY_ALREADY_ARCHIVED',
  // §3 camadas, finalidade e exportação
  'DASH.LAYER_FORBIDDEN',
  'DASH.LAYER_N3_NEVER',
  'DASH.PURPOSE_REQUIRED',
  'DASH.PURPOSE_INVALID',
  'DASH.DOMAIN_SCOPE_MISMATCH',
  'DASH.CLASSIFICATION_MISSING',
  'DASH.EXPORT_LAYER_EXCEEDED',
  'DASH.EXPORT_N3_FORBIDDEN',
  'DASH.EXPORT_VOLUME_APPROVAL_REQUIRED',
  'DASH.EXPORT_FORMAT_NOT_OPEN',
  'DASH.EXPORT_PURPOSE_REQUIRED',
  // §4 supressão e dados abertos
  'DASH.CELL_SUPPRESSED',
  'DASH.CELL_THRESHOLD_UNDEFINED',
  'DASH.DATASET_REQUIREMENTS_UNMET',
  'DASH.OPEN_DATA_PARAMETERIZED_FORBIDDEN',
  'DASH.RANKING_OF_PERSONS_FORBIDDEN',
  // §5 indicadores, relatórios e fontes
  'DASH.INDICATOR_NOT_IN_CATALOG',
  'DASH.INDICATOR_CLOCK_CODE_INVALID',
  'DASH.INDICATOR_THRESHOLD_NOT_CALIBRATED',
  'DASH.INDICATOR_TARGET_AND_CEILING_MIXED',
  'DASH.INDICATOR_LATENCY_INVALID',
  'DASH.REPORT_STATE_INVALID',
  'DASH.REPORT_TYPE_INVALID',
  'DASH.REPORT_FILE_HASH_MISMATCH',
  'DASH.SOURCE_UNAVAILABLE',
  'DASH.SOURCE_HEARTBEAT_UNDEFINED',
  'DASH.PANEL_BLOCKED_BY_DECISION',
  // §6 transversais
  'DASH.AUTH_REQUIRED',
  'DASH.FORBIDDEN_ACTION',
  'DASH.TENANT_MISMATCH',
  'DASH.VALIDATION_FAILED',
  'DASH.ENUM_INVALID',
  'DASH.IF_MATCH_REQUIRED',
  'DASH.VERSION_CONFLICT',
  'DASH.IDEMPOTENCY_REPLAY',
  'DASH.INTERNAL',
] as const;

export type DashErrorCode = (typeof DASH_ERROR_CODES)[number];

export function isDashErrorCode(value: unknown): value is DashErrorCode {
  return (DASH_ERROR_CODES as readonly unknown[]).includes(value);
}

/** `'dashboard.errors.' + código sem `DASH.` em minúsculas` (M5; catálogo §7). */
export function messageKeyFor(code: string): string {
  return `dashboard.errors.${code.replace(DASH_ERROR_PREFIX, '').toLowerCase()}`;
}
